INSERT INTO `items` (`name`, `label`, `weight`) VALUES
	('koi_grilled_salmon', 'Koi Grilled Salmon', 1),
	('koi_lobster_tail', 'Koi Lobster Tail', 1),
	('koi_shrimp_scampi', 'Koi Shrimp Scampi', 1),
	('koi_seared_scallops', 'Koi Seared Scallops', 1),
	('koi_crab_cakes', 'Koi Crab Cakes', 1),
	('koi_mojito', 'Koi Mojito', 1),
	('koi_pina_colada', 'Koi Piña Colada', 1),
	('koi_margarita', 'Koi Margarita', 1),
	('koi_espresso_martini', 'Koi Espresso Martini', 1),
	('koi_arnold_palmer', 'Koi Arnold Palmer', 1),
	('koi_ribeye_steak', 'Koi Ribeye Steak', 1),
	('koi_filet_mignon', 'Koi Filet Mignon', 1),
	('koi_t_bone_steak', 'Koi T-Bone Steak', 1),
	('koi_tomahawk_steak', 'Koi Tomahawk Steak', 1),
	('koi_new_york_strip', 'Koi New York Strip', 1),
	('koi_tiramisu', 'Koi Tiramisu', 1),
	('koi_cheesecake', 'Koi Cheesecake', 1),
	('koi_chocolate_lava_cake', 'Koi Chocolate Lava Cake', 1),
	('koi_creme_brulee', 'Koi Creme Brulee', 1),
	('koi_key_lime_pie', 'Koi Key Lime Pie', 1),
	('koi_salt', 'Salt', 1),
	('koi_dill_butter', 'Dill Butter', 1),
	('koi_clarified_butter', 'Clarified Butter', 1),
	('koi_white_wine', 'White Wine', 1),
	('koi_truffle_oil', 'Truffle Oil', 1),
	('koi_old_bay_seasoning', 'Old Bay Seasoning', 1),
	('koi_sugar', 'Sugar', 1),
	('koi_fresh_mint_leaves', 'Fresh Mint Leaves', 1),
	('koi_coconut_cream', 'Coconut Cream', 1),
	('koi_triple_sec', 'Triple Sec', 1),
	('koi_coffee_liquor_kahlua', 'Coffee Liquor Kahlua', 1),
	('koi_fresh_lemonade', 'Fresh Lamonade', 1),
	('koi_black_pepper', 'Black Pepper', 1),
	('koi_herb_butter', 'Herb Butter', 1),
	('koi_bearnaise_sauce', 'Béarnaise Sauce', 1),
	('koi_steakhouse_dry_rub', 'Steakhouse Dry Rub', 1),
	('koi_smoked_sea_salt', 'Smoked Sea Salt', 1),
	('koi_red_wine_reduction', 'Red Wine Reduction', 1),
	('koi_flour', 'Flour', 1),
	('koi_mascarpone_cheese', 'Mascarpone Cheese', 1),
	('koi_graham_cracker_crust', 'Graham Cracker Crust', 1),
	('koi_molten_ganache_filling', 'Molten Ganache Filling', 1),
	('koi_caramelized_sugar_topping', 'Caramelized Sugar Topping', 1),
	('koi_icecubes', 'Koi Ice Cubes', 1),
	('koi_waterbottle', 'Koi Water bottle', 1),
	('koi_emptycup', 'Koi Empty Cup', 1),
	('koi_key_lime_juice', 'Key Lime Juice', 1);