    -- ### Dusa Hunting ###
    WEAPON_DHR31 = { name = 'WEAPON_DHR31', label = "Hunting Rifle", weight = 100, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'WEAPON_DHR31.png', unique = true, useable = true, description = "" },
    
    campfire = { name = 'campfire', label = "Campfire", weight = 100, type = 'item', ammotype = nil, image = 'campfire.png', unique = true, useable = true, description = "" },

    primitive_grill = { name = 'primitive_grill', label = "Primitive Grill", weight = 100, type = 'item', ammotype = nil, image = 'primitive_grill.png', unique = true, useable = true, description = "" },

    advanced_grill = { name = 'advanced_grill', label = "Advanced Grill", weight = 100, type = 'item', ammotype = nil, image = 'advanced_grill.png', unique = true, useable = true, description = "" },

    hunting_bait = { name = 'hunting_bait', label = "Hunting Bait", weight = 100, type = 'item', ammotype = nil, image = 'hunting_bait.png', unique = true, useable = true, description = "" },

    hunting_license = { name = 'hunting_license', label = 'Hunting License', weight = 100, type = 'item', ammotype = nil, image = 'hunting_license.png', unique = true, useable = true, description = "" },

    -- ### Dusa Hunting Animal Parts ###
    deer_beef = { name = 'deer_beef', label = 'Deer Beef', weight = 100, type = 'item', ammotype = nil, image = 'deer_beef.png', unique = true, useable = true, description = "" },
    deer_rib = { name = 'deer_rib', label = 'Deer Rib', weight = 100, type = 'item', ammotype = nil, image = 'deer_rib.png', unique = true, useable = true, description = "" },
    deer_leg = { name = 'deer_leg', label = 'Deer Leg', weight = 100, type = 'item', ammotype = nil, image = 'deer_leg.png', unique = true, useable = true, description = "" },
    rabbit_body = { name = 'rabbit_body', label = 'Rabbit Body', weight = 100, type = 'item', ammotype = nil, image = 'rabbit_body.png', unique = true, useable = true, description = "" },
    rabbit_leg = { name = 'rabbit_leg', label = 'Rabbit Leg', weight = 100, type = 'item', ammotype = nil, image = 'rabbit_leg.png', unique = true, useable = true, description = "" },
    rabbit_beef = { name = 'rabbit_beef', label = 'Rabbit Beef', weight = 100, type = 'item', ammotype = nil, image = 'rabbit_beef.png', unique = true, useable = true, description = "" },
    bear_beef = { name = 'bear_beef', label = 'Bear Beef', weight = 100, type = 'item', ammotype = nil, image = 'bear_beef.png', unique = true, useable = true, description = "" },
    bear_rib = { name = 'bear_rib', label = 'Bear Rib', weight = 100, type = 'item', ammotype = nil, image = 'bear_rib.png', unique = true, useable = true, description = "" },
    bear_leg = { name = 'bear_leg', label = 'Bear Leg', weight = 100, type = 'item', ammotype = nil, image = 'bear_leg.png', unique = true, useable = true, description = "" },
    redpanda_body = { name = 'redpanda_body', label = 'Red Panda Body', weight = 100, type = 'item', ammotype = nil, image = 'redpanda_body.png', unique = true, useable = true, description = "" },
    redpanda_leg = { name = 'redpanda_leg', label = 'Red Panda Leg', weight = 100, type = 'item', ammotype = nil, image = 'redpanda_leg.png', unique = true, useable = true, description = "" },
    redpanda_beef = { name = 'redpanda_beef', label = 'Red Panda Beef', weight = 100, type = 'item', ammotype = nil, image = 'redpanda_beef.png', unique = true, useable = true, description = "" },
    boar_leg = { name = 'boar_leg', label = 'Boar Leg', weight = 100, type = 'item', ammotype = nil, image = 'boar_leg.png', unique = true, useable = true, description = "" },
    boar_beef = { name = 'boar_beef', label = 'Boar Beef', weight = 100, type = 'item', ammotype = nil, image = 'boar_beef.png', unique = true, useable = true, description = "" },
    boar_rib = { name = 'boar_rib', label = 'Boar Rib', weight = 100, type = 'item', ammotype = nil, image = 'boar_rib.png', unique = true, useable = true, description = "" },
    coyote_beef = { name = 'coyote_beef', label = 'Coyote Beef', weight = 100, type = 'item', ammotype = nil, image = 'coyote_beef.png', unique = true, useable = true, description = "" },
    coyote_rib = { name = 'coyote_rib', label = 'Coyote Rib', weight = 100, type = 'item', ammotype = nil, image = 'coyote_rib.png', unique = true, useable = true, description = "" },
    coyote_leg = { name = 'coyote_leg', label = 'Coyote Leg', weight = 100, type = 'item', ammotype = nil, image = 'coyote_leg.png', unique = true, useable = true, description = "" },
    mtlion_beef = { name = 'mtlion_beef', label = 'Mountain Lion Beef', weight = 100, type = 'item', ammotype = nil, image = 'mtlion_beef.png', unique = true, useable = true, description = "" },
    mtlion_rib = { name = 'mtlion_rib', label = 'Mountain Lion Rib', weight = 100, type = 'item', ammotype = nil, image = 'mtlion_rib.png', unique = true, useable = true, description = "" },
    mtlion_leg = { name = 'mtlion_leg', label = 'Mountain Lion Leg', weight = 100, type = 'item', ammotype = nil, image = 'mtlion_leg.png', unique = true, useable = true, description = "" },
    lion_beef = { name = 'lion_beef', label = 'Lion Beef', weight = 100, type = 'item', ammotype = nil, image = 'lion_beef.png', unique = true, useable = true, description = "" },
    lion_rib = { name = 'lion_rib', label = 'Lion Rib', weight = 100, type = 'item', ammotype = nil, image = 'lion_rib.png', unique = true, useable = true, description = "" },
    lion_leg = { name = 'lion_leg', label = 'Lion Leg', weight = 100, type = 'item', ammotype = nil, image = 'lion_leg.png', unique = true, useable = true, description = "" },
    lion_body = { name = 'lion_body', label = 'Lion Body', weight = 100, type = 'item', ammotype = nil, image = 'lion_body.png', unique = true, useable = true, description = "" },
    oryx_beef = { name = 'oryx_beef', label = 'Oryx Beef', weight = 100, type = 'item', ammotype = nil, image = 'oryx_beef.png', unique = true, useable = true, description = "" },
    oryx_rib = { name = 'oryx_rib', label = 'Oryx Rib', weight = 100, type = 'item', ammotype = nil, image = 'oryx_rib.png', unique = true, useable = true, description = "" },
    oryx_leg = { name = 'oryx_leg', label = 'Oryx Leg', weight = 100, type = 'item', ammotype = nil, image = 'oryx_leg.png', unique = true, useable = true, description = "" },
    antelope_beef = { name = 'antelope_beef', label = 'Antelope Beef', weight = 100, type = 'item', ammotype = nil, image = 'antelope_beef.png', unique = true, useable = true, description = "" },
    antelope_rib = { name = 'antelope_rib', label = 'Antelope Rib', weight = 100, type = 'item', ammotype = nil, image = 'antelope_rib.png', unique = true, useable = true, description = "" },
    antelope_leg = { name = 'antelope_leg', label = 'Antelope Leg', weight = 100, type = 'item', ammotype = nil, image = 'antelope_leg.png', unique = true, useable = true, description = "" },

    -- Cooked Items
    deer_beef_cooked = { name = 'deer_beef_cooked', label = 'Cooked Deer Beef', weight = 100, type = 'item', ammotype = nil, image = 'deer_beef_cooked.png', unique = true, useable = true, description = "" },
    deer_rib_cooked = { name = 'deer_rib_cooked', label = 'Cooked Deer Rib', weight = 100, type = 'item', ammotype = nil, image = 'deer_rib_cooked.png', unique = true, useable = true, description = "" },
    deer_leg_cooked = { name = 'deer_leg_cooked', label = 'Cooked Deer Leg', weight = 100, type = 'item', ammotype = nil, image = 'deer_leg_cooked.png', unique = true, useable = true, description = "" },
    rabbit_body_cooked = { name = 'rabbit_body_cooked', label = 'Cooked Rabbit Body', weight = 100, type = 'item', ammotype = nil, image = 'rabbit_body_cooked.png', unique = true, useable = true, description = "" },
    rabbit_leg_cooked = { name = 'rabbit_leg_cooked', label = 'Cooked Rabbit Leg', weight = 100, type = 'item', ammotype = nil, image = 'rabbit_leg_cooked.png', unique = true, useable = true, description = "" },
    rabbit_beef_cooked = { name = 'rabbit_beef_cooked', label = 'Cooked Rabbit Beef', weight = 100, type = 'item', ammotype = nil, image = 'rabbit_beef_cooked.png', unique = true, useable = true, description = "" },
    bear_beef_cooked = { name = 'bear_beef_cooked', label = 'Cooked Bear Beef', weight = 100, type = 'item', ammotype = nil, image = 'bear_beef_cooked.png', unique = true, useable = true, description = "" },
    bear_rib_cooked = { name = 'bear_rib_cooked', label = 'Cooked Bear Rib', weight = 100, type = 'item', ammotype = nil, image = 'bear_rib_cooked.png', unique = true, useable = true, description = "" },
    bear_leg_cooked = { name = 'bear_leg_cooked', label = 'Cooked Bear Leg', weight = 100, type = 'item', ammotype = nil, image = 'bear_leg_cooked.png', unique = true, useable = true, description = "" },
    redpanda_body_cooked = { name = 'redpanda_body_cooked', label = 'Cooked Red Panda Body', weight = 100, type = 'item', ammotype = nil, image = 'redpanda_body_cooked.png', unique = true, useable = true, description = "" },
    redpanda_leg_cooked = { name = 'redpanda_leg_cooked', label = 'Cooked Red Panda Leg', weight = 100, type = 'item', ammotype = nil, image = 'redpanda_leg_cooked.png', unique = true, useable = true, description = "" },
    redpanda_beef_cooked = { name = 'redpanda_beef_cooked', label = 'Cooked Red Panda Beef', weight = 100, type = 'item', ammotype = nil, image = 'redpanda_beef_cooked.png', unique = true, useable = true, description = "" },
    boar_leg_cooked = { name = 'boar_leg_cooked', label = 'Cooked Boar Leg', weight = 100, type = 'item', ammotype = nil, image = 'boar_leg_cooked.png', unique = true, useable = true, description = "" },
    boar_beef_cooked = { name = 'boar_beef_cooked', label = 'Cooked Boar Beef', weight = 100, type = 'item', ammotype = nil, image = 'boar_beef_cooked.png', unique = true, useable = true, description = "" },
    boar_rib_cooked = { name = 'boar_rib_cooked', label = 'Cooked Boar Rib', weight = 100, type = 'item', ammotype = nil, image = 'boar_rib_cooked.png', unique = true, useable = true, description = "" },
    coyote_beef_cooked = { name = 'coyote_beef_cooked', label = 'Cooked Coyote Beef', weight = 100, type = 'item', ammotype = nil, image = 'coyote_beef_cooked.png', unique = true, useable = true, description = "" },
    coyote_rib_cooked = { name = 'coyote_rib_cooked', label = 'Cooked Coyote Rib', weight = 100, type = 'item', ammotype = nil, image = 'coyote_rib_cooked.png', unique = true, useable = true, description = "" },
    coyote_leg_cooked = { name = 'coyote_leg_cooked', label = 'Cooked Coyote Leg', weight = 100, type = 'item', ammotype = nil, image = 'coyote_leg_cooked.png', unique = true, useable = true, description = "" },
    mtlion_beef_cooked = { name = 'mtlion_beef_cooked', label = 'Cooked Mountain Lion Beef', weight = 100, type = 'item', ammotype = nil, image = 'mtlion_beef_cooked.png', unique = true, useable = true, description = "" },
    mtlion_rib_cooked = { name = 'mtlion_rib_cooked', label = 'Cooked Mountain Lion Rib', weight = 100, type = 'item', ammotype = nil, image = 'mtlion_rib_cooked.png', unique = true, useable = true, description = "" },
    mtlion_leg_cooked = { name = 'mtlion_leg_cooked', label = 'Cooked Mountain Lion Leg', weight = 100, type = 'item', ammotype = nil, image = 'mtlion_leg_cooked.png', unique = true, useable = true, description = "" },
    lion_beef_cooked = { name = 'lion_beef_cooked', label = 'Cooked Lion Beef', weight = 100, type = 'item', ammotype = nil, image = 'lion_beef_cooked.png', unique = true, useable = true, description = "" },
    lion_rib_cooked = { name = 'lion_rib_cooked', label = 'Cooked Lion Rib', weight = 100, type = 'item', ammotype = nil, image = 'lion_rib_cooked.png', unique = true, useable = true, description = "" },
    lion_leg_cooked = { name = 'lion_leg_cooked', label = 'Cooked Lion Leg', weight = 100, type = 'item', ammotype = nil, image = 'lion_leg_cooked.png', unique = true, useable = true, description = "" },
    lion_body_cooked = { name = 'lion_body_cooked', label = 'Cooked Lion Body', weight = 100, type = 'item', ammotype = nil, image = 'lion_body_cooked.png', unique = true, useable = true, description = "" },
    oryx_beef_cooked = { name = 'oryx_beef_cooked', label = 'Cooked Oryx Beef', weight = 100, type = 'item', ammotype = nil, image = 'oryx_beef_cooked.png', unique = true, useable = true, description = "" },
    oryx_rib_cooked = { name = 'oryx_rib_cooked', label = 'Cooked Oryx Rib', weight = 100, type = 'item', ammotype = nil, image = 'oryx_rib_cooked.png', unique = true, useable = true, description = "" },
    oryx_leg_cooked = { name = 'oryx_leg_cooked', label = 'Cooked Oryx Leg', weight = 100, type = 'item', ammotype = nil, image = 'oryx_leg_cooked.png', unique = true, useable = true, description = "" },
    antelope_beef_cooked = { name = 'antelope_beef_cooked', label = 'Cooked Antelope Beef', weight = 100, type = 'item', ammotype = nil, image = 'antelope_beef_cooked.png', unique = true, useable = true, description = "" },
    antelope_rib_cooked = { name = 'antelope_rib_cooked', label = 'Cooked Antelope Rib', weight = 100, type = 'item', ammotype = nil, image = 'antelope_rib_cooked.png', unique = true, useable = true, description = "" },
    antelope_leg_cooked = { name = 'antelope_leg_cooked', label = 'Cooked Antelope Leg', weight = 100, type = 'item', ammotype = nil, image = 'antelope_leg_cooked.png', unique = true, useable = true, description = "" },

    hide = { name = 'hide', label = "Hide", weight = 100, type = 'item', ammotype = nil, image = 'hide.png', unique = true, useable = true, description = "" },

    binocular = { name = 'binocular', label = 'Binocular', weight = 100, type = 'item', ammotype = nil, image = 'binocular.png', unique = true, useable = true, description = "" },

    hunting_trap = { name = 'hunting_trap', label = 'Hunting Trap', weight = 100, type = 'item', ammotype = nil, image = 'hunting_trap.png', unique = true, useable = true, description = "" },

    hunting_laptop = { name = 'hunting_laptop', label = 'Hunting Laptop', weight = 100, type = 'item', ammotype = nil, image = 'hunting_laptop.png', unique = true, useable = true, description = "" },