import React, {
  Context,
  createContext,
  useContext,
  useEffect,
  useState,
} from "react"
import { useNuiEvent } from "../hooks/useNuiEvent"
import { debugData } from "./../utils/debugData"

export const LanguageContext = createContext()

debugData([
  {
    action: "language",
    data: {
      same: "SAME",
      OPP: "OPP",
      XMIT: "XMIT",
      Lock: "Lock",
      Fast: "Fast",
      Rear: "Rear",
      Front: "Front",
      Speed: "Speed",
      fastLimit: "Fast Limit",
      fasLimitReset: "Fast Limit Reset",
      toggleRadar: "Toggle Radar",
      plateLock: "Plate Lock",
      antennaScan: "Antenna Scan",
      radarSettings: "Radar Settings",
      radarDec: "Radar Settings Description",
      frontAntena: "Front Antena",
      turnOnOff: "Turn On/Off",
      enterValue: "Enter Value",
      resetSettings: "Reset Settings",
      rearAntena: "Rear Antena",
      customizableRadar: "Customizable Radar",
      editRadar: "Edit Radar",
      edit: "Edit",
      size: "Size",
      on: "On",
      off: "Off",
      reset: "Reset",
      misc: "Misc",
      draws: "Draws",
      drawsDesc: "Draws Description",
      save: "Save",
      create: "Create",
      cancel: "Cancel",
      title: "Title",
      description: "Description",
      lowPrioty: "Low Prioty",
      mediumPrioty: "Medium Prioty",
      highPrioty: "High Prioty",
      bodyCamList: "BodyCam List",
      bodyCamDesc: "Body Cam Description",
      clickToWatch: "Click to watch",
      rec: "REC",
      bodyCamShowDesc: "AXON BODY 3",
      gpschannels: "GPS Channels",
      gpsDesc: "GPS Description",
      commonChannels: "Common Channels",
      heistChannels: "Heist Channels",
      connectChannel: "Connect Channel",
      disconnectChannel: "Disconnect Channel",
      gpsName: "GPS Name",
      enterName: "Enter Name",
      everyone: "Everyone",
      createChannel: "Create Channel",
      radioFrequences: "Radio Frequences",
      radioDesc: "Radio Description",
      radioName: "Radio Name",
      radioFrequency: "Radio Frequency",
      enterFrequency: "Enter Frequency",
      createFrequency: "Create Frequency",
      frequencyAlert: "⚠️ This frequency is already used",
      settings: "Settings",
      settingsDesc: "Settings Description",
      alertClearTime: "Alert Clear Time",
      callSign: "Callsign",
      alertNotification: "Alert Notification",
      manage: "Manage",
      addaCamera: "Add a Camera",
      addCameraDesc: "Add Camera Description",
      cameraList: "Camera List",
      cameraListDesc: "Camera List Description",
      cameraName: "Camera Name",
      setCameraName: "Set Camera Name",
      cameraType: "Camera Type",
      setCameraType: "Set Camera Type",
      selectType: "Select Type",
      add: "Add",
      searchCamera: "Search Camera",
      hours: "Hours",
      minutes: "Minutes",
      ago: "Ago",
      availableAgents: "Available Agents",
      searchUser: "Search User",
      acceptCall: "Accept Call",
      delete: "Delete",
      low: "Low",
      medium: "Medium",
      high: "High",
      emergencyAlert: "Emergency Alert",
      unitName: "Unit Name",
      setaUnitName: "Set a Unit Name",
      maxAgents: "Max Agents",
      setaMaxAgents: "Set a Max Agents",
      enterMaxAgents: "Enter Max Agents",
      createUnit: "Create Unit",
      createUnitDesc: "Create Unit Description",
      deleteUnit: "Delete Unit",
      settingsUnit: "Settings Unit",
      settingsUnitDesc: "Settings Unit Description",
      agentsFound: "Agents Found",
      mapFilter: "Map Filter",
      bcso: "BCSO",
      police: "Police",
      sheriff: "Sheriff",
      highway: "Highway",
      state: "State",
      ranger: "Ranger",
      ambulance: "Ambulance",
      alertReceviver: "Alert Receviver",
      alertReceviverDesc: "Alert Receviver Description",
      availableUnits: "Available Units",
      unitsFound: "Units Found",
      person: "Person",
      radio: "Radio",
      gps: "GPS",
      deleteCall: "Delete Call",
      dispatchManager: "Dispatch Manager",
      selectManager: "Select Manager",
      notEntered: "Not Connected",
      time: "Time",
      code: "Code",
      alertUnitDesc: "Subjected Units",
      unit: "Unit",
      dispatch: "Dispatch",
      markedMap: "Alert location marked on map",
    },
  },
])

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState({
    same: "SAME",
    OPP: "OPP",
    XMIT: "XMIT",
    Lock: "Lock",
    Fast: "Fast",
    Rear: "Rear",
    Front: "Front",
    Speed: "Speed",
    fastLimit: "Fast Limit",
    fasLimitReset: "Fast Limit Reset",
    toggleRadar: "Toggle Radar",
    plateLock: "Plate Lock",
    antennaScan: "Antenna Scan",
    radarSettings: "Radar Settings",
    radarDec: "Radar Settings Description",
    frontAntena: "Front Antena",
    turnOnOff: "Turn On/Off",
    enterValue: "Enter Value",
    resetSettings: "Reset Settings",
    rearAntena: "Rear Antena",
    customizableRadar: "Customizable Radar",
    editRadar: "Edit Radar",
    edit: "Edit",
    size: "Size",
    on: "On",
    off: "Off",
    reset: "Reset",
    misc: "Misc",
    draws: "Draws",
    drawsDesc: "Draws Description",
    save: "Save",
    create: "Create",
    cancel: "Cancel",
    title: "Title",
    description: "Description",
    lowPrioty: "Low Prioty",
    mediumPrioty: "Medium Prioty",
    highPrioty: "High Prioty",
    bodyCamList: "BodyCam List",
    bodyCamDesc: "Body Cam Description",
    clickToWatch: "Click to watch",
    rec: "REC",
    bodyCamShowDesc: "AXON BODY 3",
    gpschannels: "GPS Channels",
    gpsDesc: "GPS Description",
    commonChannels: "Common Channels",
    heistChannels: "Heist Channels",
    connectChannel: "Connect Channel",
    disconnectChannel: "Disconnect Channel",
    gpsName: "GPS Name",
    enterName: "Enter Name",
    everyone: "Everyone",
    createChannel: "Create Channel",
    radioFrequences: "Radio Frequences",
    radioDesc: "Radio Description",
    radioName: "Radio Name",
    radioFrequency: "Radio Frequency",
    enterFrequency: "Enter Frequency",
    createFrequency: "Create Frequency",
    frequencyAlert: "⚠️ This frequency is already used",
    settings: "Settings",
    settingsDesc: "Settings Description",
    alertClearTime: "Alert Clear Time",
    callSign: "Callsign",
    alertNotification: "Alert Notification",
    manage: "Manage",
    addaCamera: "Add a Camera",
    addCameraDesc: "Add Camera Description",
    cameraList: "Camera List",
    cameraListDesc: "Camera List Description",
    cameraName: "Camera Name",
    setCameraName: "Set Camera Name",
    cameraType: "Camera Type",
    setCameraType: "Set Camera Type",
    selectType: "Select Type",
    add: "Add",
    searchCamera: "Search Camera",
    hours: "Hours",
    minutes: "Minutes",
    ago: "Ago",
    availableAgents: "Available Agents",
    searchUser: "Search User",
    acceptCall: "Accept Call",
    delete: "Delete",
    low: "Low",
    medium: "Medium",
    high: "High",
    emergencyAlert: "Emergency Alert",
    unitName: "Unit Name",
    setaUnitName: "Set a Unit Name",
    maxAgents: "Max Agents",
    setaMaxAgents: "Set a Max Agents",
    enterMaxAgents: "Enter Max Agents",
    createUnit: "Create Unit",
    createUnitDesc: "Create Unit Description",
    deleteUnit: "Delete Unit",
    settingsUnit: "Settings Unit",
    settingsUnitDesc: "Settings Unit Description",
    agentsFound: "Agents Found",
    mapFilter: "Map Filter",
    bcso: "BCSO",
    police: "Police",
    sheriff: "Sheriff",
    highway: "Highway",
    state: "State",
    ranger: "Ranger",
    ambulance: "Ambulance",
    alertReceviver: "Alert Receviver",
    alertReceviverDesc: "Alert Receviver Description",
    availableUnits: "Available Units",
    unitsFound: "Units Found",
    person: "Person",
    radio: "Radio",
    gps: "GPS",
    deleteCall: "Delete Call",
    dispatchManager: "Dispatch Manager",
    selectManager: "Select Manager",
    time: "Time",
    code: "Code",
    alertUnitDesc: "Subjected Unit(s)",
    unit: "Unit",
    notEntered: "Not Connected",
    dispatch: "Dispatch",

    joinGps: "You successfully joined the GPS channel.",
    leftGps: "You successfully disconnected from the GPS channel.",
    connectGps: "You successfully connected to the GPS.",
    createGps: "New GPS channel created.",
    deleteGps: "GPS channel deleted.",
    saveDraw: "The draw you created saved.",
    deleteDraw: "The draw you selected deleted.",
    deleteCamera: "Camera deleted.",
    callsignLetterLimit: "The call sign must be less than 5 characters.",
    callsignSet: "Call sign set successfully.",
    alertGUIEnabled: "Alert GUI enabled.",
    alertGUIDisabled: "Alert GUI disabled.",
    dispatchManagerSet: "New dispatch manager set to",
    settingsSaved: "Settings saved successfully.",
    joinedRadio: "You successfully joined the radio channel",
    leftRadio: "You left the radio channel",
    deleteRadio: "Radio channel deleted.",
    radioChannelCreated: "New radio channel created with the name",
    radioChannelConnected: "You successfully connected to the radio channel",
    radioChannelDisconnected: "You successfully disconnected from the radio channel",
    unitCreated: "You successfully create an unit with the name",
    unitSaved: "All changes with unit saved successfully.",
    unitDeleted: "Unit deleted successfully.",
    unitJoined: "You successfully joined the unit",
    unitLeft: "You successfully left the unit",
    markedMap: "Alert location marked on map",
  })
  const changeLanguage = (lang) => {
    setLanguage(lang)
  }

  useNuiEvent("SET_LANGUAGE", (lang) => {
    changeLanguage(lang)
  })

  return (
    <LanguageContext.Provider
      value={{ language, changeLanguage }}
    >
      {children}
    </LanguageContext.Provider>
  )
}