-- Dusa Garage Management System - Job Vehicle Configuration
-- Version: 1.0.0
-- Advanced job garage features with grade restrictions and ownership tracking
-- Auto-generated by Config Editor

Config = Config or {}

-- Job Vehicle Configuration System
Config.JobVehicles = {
    -- Ambulance Department Vehicles
    ["ambulance"] = {
        {
            vehicle = "ambulance",
            displayName = "Standard Ambulance",
            minGrade = 0,
            category = "emergency",
            description = "Basic emergency response vehicle",
            vehicleType = "car"
        },
        {
            vehicle = "firetruk",
            displayName = "Fire Truck",
            minGrade = 1,
            category = "fire",
            description = "Fire suppression and rescue vehicle",
            vehicleType = "car"
        },
        {
            vehicle = "lifeguard",
            displayName = "Lifeguard ATV",
            minGrade = 0,
            category = "beach",
            description = "Beach patrol and water rescue vehicle",
            vehicleType = "car"
        },
        {
            vehicle = "sadfsadf",
            displayName = "sadfsadfsadf",
            minGrade = 3,
            category = "speed_unit",
            description = "",
            vehicleType = "aircraft"
        }
    },

    -- Mechanic Department Vehicles
    ["mechanic"] = {
        {
            vehicle = "towtruck",
            displayName = "Tow Truck",
            minGrade = 0,
            category = "towing",
            description = "Vehicle recovery and towing service",
            vehicleType = "car"
        },
        {
            vehicle = "utillitruck3",
            displayName = "Utility Truck",
            minGrade = 2,
            category = "repair",
            description = "Mobile repair station for senior mechanics",
            vehicleType = "car"
        },
        {
            vehicle = "flatbed",
            displayName = "Test mekanik",
            minGrade = 0,
            category = "",
            description = "",
            vehicleType = "car"
        }
    },

    -- Police Department Vehicles
    ["police"] = {
        {
            vehicle = "police",
            displayName = "Polis 1",
            minGrade = 0,
            category = "patrol",
            description = "Polis Car 1",
            vehicleType = "car"
        },
        {
            vehicle = "police2",
            displayName = "Polis 2",
            minGrade = 0,
            category = "patrol",
            description = "Testdasf",
            vehicleType = "car"
        },
        {
            vehicle = "police3",
            displayName = "Police 3 Cruiser",
            minGrade = 2,
            category = "speed_unit",
            description = "",
            vehicleType = "car"
        },
        {
            vehicle = "buzzard2",
            displayName = "Buzzard",
            minGrade = 2,
            category = "patrol",
            description = "dfsadg",
            vehicleType = "aircraft"
        },
        {
            vehicle = "dinghy",
            displayName = "Dinghy",
            minGrade = 2,
            category = "speed_unit",
            description = "",
            vehicleType = "boat"
        }
    },

    -- Sheriff Department Vehicles
    ["sheriff"] = {
        {
            vehicle = "test",
            displayName = "test sheriff",
            minGrade = 0,
            category = "patrol",
            description = "",
            vehicleType = "car"
        }
    }

}
