var questions = {
    ['A']: [
        {
            "questionPhoto": 'question_1.png',
            "question": 'Can you drive on public roads in this way?',
            "a": 'Yes, if there are no other vehicles around.',
            "b": 'No.',
            "c": 'Yes, if you are confident in your skills.',
            "d": 'Yes, only outside built-up areas.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_2.png',
            "question": 'As you approach the center of a turn, you should',
            "a": 'move toward the outside of the curve.',
            "b": 'decrease the throttle.',
            "c": 'move toward the inside of the curve',
            "d": 'apply the rear brake.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_3.png',
            "question": 'When approaching an intersection, you should select a lane position to',
            "a": 'reduce your following distance.',
            "b": 'increase your visibility to other vehicle operators.',
            "c": 'increase your speed and pass quickly.',
            "d": 'do all of the above.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'What are the requirements for wearing a helmet?',
            "a": 'Helmets are not required while driving on city streets.',
            "b": 'All motorcycle riders and passengers are required to wear helmets at all times.',
            "c": 'Passengers only are required to wear helmets.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Grabbing the front brake or jamming down on the rear brake',
            "a": 'Is the best way to stop in an emergency.',
            "b": 'Is the best way to slow down when the streets are wet.',
            "c": 'Can cause the brakes to lock.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Passengers on motorcycles should',
            "a": 'Should sit as far forward as possible without crowding you.',
            "b": 'Put their feet on the ground when the motorcycle is stopped.',
            "c": 'Not ride without a back rest.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'When riding with a group of motorcyclists, a staggered formation',
            "a": 'Should be used when riding on curves.',
            "b": 'Is recommended at all times.',
            "c": 'Should not be used when entering or exiting a highway.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'You should operate the engine cut-off switch and pull in the clutch when',
            "a": 'The throttle is stuck and you cant free it.',
            "b": 'You start to lose control in a curve.',
            "c": 'The motorcycle starts to wobble.',
            "correctAnswer": 'A',
        },

        {
            "questionPhoto": 'nophoto.png',
            "question": 'Before changing lanes on a multilane road, you should check',
            "a": 'the lane next to you and the far lane.',
            "b": 'only the far lane.',
            "c": 'your signal light.',
            "d": 'only the lane next to you.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'When riding in a group, the best formation is the ___ formation.',
            "a": 'single-file.',
            "b": 'side-by-side.',
            "c": 'staggered.',
            "d": 'V-shaped.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'When making a slow, tight turn, the rider should',
            "a": 'lean in the opposite direction of the motorcycle.',
            "b": 'lean toward the front of the motorcycle.',
            "c": 'lean in the same direction as the motorcycle.',
            "d": 'keep his or her body straight while leaning the motorcycle.',
            "correctAnswer": 'D',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'If oncoming traffic is present and you are passing a line of parked cars, which lane position should you choose?',
            "a": 'Center',
            "b": 'Right',
            "c": 'Center or right',
            "d": 'Left',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Most of your motorcycles stopping power is provided by',
            "a": 'the rear brake.',
            "b": 'the front and rear brakes equally.',
            "c": 'the clutch.',
            "d": 'the front brake.',
            "correctAnswer": 'D',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'If your motorcycle starts to wobble, your best course of action is to',
            "a": 'apply the brakes quickly.',
            "b": 'close the throttle gradually.',
            "c": 'grip the handlebars tightly and flight the wobble.',
            "d": 'accelerate out of the wobble.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Surfaces that provide little traction for a motorcycle include',
            "a": 'lanes that are not often used.',
            "b": 'gravel roads.',
            "c": 'tire markings, where other vehicles have traveled.',
            "d": 'pavement that is hot from the sun.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Increase your safety at night by',
            "a": 'using the lights of the car ahead to help you see.',
            "b": 'increasing your following distance.',
            "c": 'riding with your high beam.',
            "d": 'doing all of the above.',
            "correctAnswer": 'D',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'When following a vehicle, you should maintain a ___-second following distance.',
            "a": 'two',
            "b": 'three',
            "c": 'four',
            "d": 'five',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'In a lane of traffic, how many lane positions are there for a motorcycle?',
            "a": '1',
            "b": '2',
            "c": '3',
            "d": '4',
            "correctAnswer": 'C',
        },
    ],
    ['B']: [
        {
            "questionPhoto": 'question_1.png',
            "question": 'Should you brake in such a situation?',
            "a": 'Yes, because there is enough distance to brake.',
            "b": 'No, because in a moment the traffic light will turn green.',
            "c": 'No.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_2.png',
            "question": 'Can you stop on this part of the sidewalk?',
            "a": 'Yes but only when the police stop us.',
            "b": 'Yes.',
            "c": 'Yes, a maximum of 5 minutes.',
            "d": 'No.',
            "correctAnswer": 'D',
        },
        {
            "questionPhoto": 'question_3.png',
            "question": 'Can you make a left turn in this situation?',
            "a": 'Yes.',
            "b": 'No.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_4.png',
            "question": 'Can you turn right at this point without stopping?',
            "a": 'Yes, when vehicles are not coming from the left side',
            "b": 'No, the sign requires the vehicle to stop absolutely.',
            "c": 'Yes, this sign means my priority.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_5.png',
            "question": 'What is the maximum speed you can travel on this road?',
            "a": '140 km/h',
            "b": '110 km/h',
            "c": '120 km/h',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_6.png',
            "question": 'Can the road shown in the photo be traveled in both directions?',
            "a": 'Yes, if it does not jeopardize the safety of other traffic participants.',
            "b": 'No.',
            "c": 'Yes.',
            "d": 'Only cabs can move in the opposite direction',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_7.png',
            "question": 'Can you turn left at this point?',
            "a": 'Yes.',
            "b": 'No.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_8.png',
            "question": 'Which of these pavement markings separates two lanes traveling in the same direction?',
            "a": 'A',
            "b": 'B',
            "c": 'None of the above',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_9.png',
            "question": 'This sign means:',
            "a": 'Pedestrian crossing ahead',
            "b": 'Pedestrians must not cross here',
            "c": 'Pedestrians walking along the road ahead',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_10.png',
            "question": 'This sign means:',
            "a": 'Do not enter.',
            "b": 'Reserved parking for persons with disabilities.',
            "c": 'Yield the right-of-way.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Can you pass another vehicle when approaching a curve or a hill?',
            "a": 'Yes, but you may only pass on the right.',
            "b": 'No, never.',
            "c": 'Yes, but only if there is enough space.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Which of the following places is a U-turn allowed?',
            "a": 'On the railroad crossing',
            "b": 'Across a double yellow line',
            "c": 'On a one-way street',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'You should cut your speed in half when the road is ___.',
            "a": 'wet',
            "b": 'icy',
            "c": 'packed with snow',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'When driving in fog, rain, or snow, use ___.',
            "a": 'low beams',
            "b": 'fog lights only',
            "c": 'high beams',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'A broken yellow centerline means that:',
            "a": 'Passing is not permitted.',
            "b": 'Passing on the left is permitted when the way ahead is clear.',
            "c": 'Passing on the right is permitted when the way ahead is clear.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Alcohol is',
            "a": 'A stimulant.',
            "b": 'An antihistamine.',
            "c": 'A depressant.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Before you change lanes, you should check your mirrors and',
            "a": 'Glance over your shoulder',
            "b": 'Never look over your right shoulder',
            "c": 'Always slow down in your traffic lane',
            "correctAnswer": 'A',
        },

    ],
    ['C']: [
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Which of the following should you NOT do if you experience a tire failure?',
            "a": 'Be aware that a tire has failed.',
            "b": 'Apply the brakes hard and immediately.',
            "c": 'Hold the steering wheel firmly.',
            "d": 'Stay off the brake pedal.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Flags or lights are required on projecting loads that extend',
            "a": '56 inches or more beyond the rear body.',
            "b": '3 or more feet beyond the rear body.',
            "c": '4 or more feet beyond the rear body.',
            "d": '6 or more feet beyond the rear body.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'Which of these equals the total stopping distance?',
            "a": 'Reaction distance + breaking distance',
            "b": 'Reaction distance + breaking distance + signal distance',
            "c": 'Perception distance + reaction distance + breaking distance',
            "d": 'Perception distance + reaction distance',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'To help you stay alert and safe while driving, you should',
            "a": 'drink coffee if you get drowsy.',
            "b": 'avoid medications whose warning labels mention drowsiness.',
            "c": 'have a whiskey to brace yourself.',
            "d": 'roll down your windows to get fresh air.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'nophoto.png',
            "question": 'An A: B: C type fire extinguisher is designed to work on which types of fires?',
            "a": 'Wood, paper and cloth',
            "b": 'Gasoline',
            "c": 'Electrical',
            "d": 'All of the above',
            "correctAnswer": 'D',
        },
    ],
}