DELETE FROM items WHERE name = 'WEAPON_BAR15'; # DO NOT INSTALL IF USING OX LIKE READ THE INSTALL GUIDE
DELETE FROM items WHERE name = 'WEAPON_AXE';
DELETE FROM items WHERE name = 'WEAPON_BLACKARP';
DELETE FROM items WHERE name = 'WEAPON_BLACKSTORM';
DELETE FROM items WHERE name = 'WEAPON_BLACKTOMMY';
DELETE FROM items WHERE name = 'WEAPON_BLUETITANS';
DELETE FROM items WHERE name = 'WEAPON_CHAIR';
DELETE FROM items WHERE name = 'WEAPON_DMK18';
DELETE FROM items WHERE name = 'WEAPON_FALCON57';
DELETE FROM items WHERE name = 'WEAPON_TITAN21';
DELETE FROM items WHERE name = 'WEAPON_TITAN41';
DELETE FROM items WHERE name = 'WEAPON_TITANBEAMS';
DELETE FROM items WHERE name = 'WEAPON_HUNTERB80L';
DELETE FROM items WHERE name = 'WEAPON_ILLTITAN17';
DELETE FROM items WHERE name = 'WEAPON_VIPERVECTOR';
DELETE FROM items WHERE name = 'WEAPON_LBTARP';
DELETE FROM items WHERE name = 'WEAPON_MGTITAN';
DELETE FROM items WHERE name = 'WEAPON_MIDASTITAN';
DELETE FROM items WHERE name = 'WEAPON_MAVERICK500';
DELETE FROM items WHERE name = 'WEAPON_PHOENIX210';
DELETE FROM items WHERE name = 'WEAPON_RAV7';
DELETE FROM items WHERE name = 'WEAPON_REDARP';
DELETE FROM items WHERE name = 'WEAPON_REDM4A1';
DELETE FROM items WHERE name = 'WEAPON_WINRANGE590';
DELETE FROM items WHERE name = 'WEAPON_RANGERP40';
DELETE FROM items WHERE name = 'WEAPON_TPATRIOT1911';
DELETE FROM items WHERE name = 'WEAPON_TARP';
DELETE FROM items WHERE name = 'WEAPON_TT19';
DELETE FROM items WHERE name = 'WEAPON_TAC9S';
DELETE FROM items WHERE name = 'WEAPON_WOARP';

DELETE FROM items WHERE name = 'COMPONENT_AT_BAR15_SCOPE_MEDIUM';
DELETE FROM items WHERE name = 'COMPONENT_AT_AR_BAR15_FLSH';
DELETE FROM items WHERE name = 'COMPONENT_AT_AR_BAR15_AFGRIP';
DELETE FROM items WHERE name = 'COMPONENT_BLACKSTORM_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_BLACKTOMMY_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_BLUETITANS_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_BLUETITANS_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_BLUETITANS_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_BLUETITANS_CLIP_05';
DELETE FROM items WHERE name = 'COMPONENT_AT_DMK18_SCOPE_MEDIUM';
DELETE FROM items WHERE name = 'COMPONENT_AT_AR_DMK18_FLSH';
DELETE FROM items WHERE name = 'COMPONENT_AT_AR_DMK18_AFGRIP';
DELETE FROM items WHERE name = 'COMPONENT_AT_AR_DMK18_SUPP';
DELETE FROM items WHERE name = 'COMPONENT_TITAN41_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_TITANBEAMS_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_TITANBEAMS_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_TITANBEAMS_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_TITANBEAMS_CLIP_05';
DELETE FROM items WHERE name = 'COMPONENT_ILLTITAN17_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_ILLTITAN17_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_ILLTITAN17_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_ILLTITAN17_CLIP_05';
DELETE FROM items WHERE name = 'COMPONENT_LBTANARP_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_LBTANARP_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_LBTANARP_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_MGTITAN_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_MGTITAN_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_MGTITAN_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_MGTITAN_CLIP_05';
DELETE FROM items WHERE name = 'COMPONENT_MIDASTITAN_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_MIDASTITAN_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_MIDASTITAN_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_MIDASTITAN_CLIP_05';
DELETE FROM items WHERE name = 'COMPONENT_REDARP_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_REDARP_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_REDARP_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_REDM4A1_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_AT_AR_REDM4A1_SUPP';
DELETE FROM items WHERE name = 'COMPONENT_TANARP_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_TANARP_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_TANARP_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_TT19_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_TT19_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_TT19_CLIP_04';
DELETE FROM items WHERE name = 'COMPONENT_TT19_CLIP_05';
DELETE FROM items WHERE name = 'COMPONENT_TAC9S_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_WOARP_CLIP_02';
DELETE FROM items WHERE name = 'COMPONENT_WOARP_CLIP_03';
DELETE FROM items WHERE name = 'COMPONENT_WOARP_CLIP_04';

INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('WEAPON_BAR15', 'AR-15', 2, 0, 1),
('WEAPON_AXE', 'AXE', 1, 0, 1),
('WEAPON_BLACKARP', 'BLACK ARP', 2, 0, 1),
('WEAPON_BLACKSTORM', 'BLACK STORM', 2, 0, 1),
('WEAPON_BLACKTOMMY', 'BLACK TOMMY', 2, 0, 1),
('WEAPON_BLUETITANS', 'BLUE TITAN SWITCH', 1, 0, 1),
('WEAPON_CHAIR', 'BRAWL CHAIR', 1, 0, 1),
('WEAPON_DMK18', 'DESERET MK18', 1, 0, 1),
('WEAPON_FALCON57', 'FALCON 57', 1, 0, 1),
('WEAPON_TITAN21', 'TITAN 21', 1, 0, 1),
('WEAPON_TITAN41', 'TITAN 41', 1, 0, 1),
('WEAPON_TITANBEAMS', 'TITAN BEAM SWITCH', 1, 0, 1),
('WEAPON_HUNTERB80L', 'HUNTER B80L', 1, 0, 1),
('WEAPON_ILLTITAN17', 'ILLEGAL TITAN 17', 1, 0, 1),
('WEAPON_VIPERVECTOR', 'VIPER VECTOR', 1, 0, 1),
('WEAPON_LBTARP', 'LB TAN ARP', 1, 0, 1),
('WEAPON_MGTITAN', 'MG TITAN', 1, 0, 1),
('WEAPON_MIDASTITAN', 'MIDAS TITAN', 1, 0, 1),
('WEAPON_MAVERICK500', 'MAVERICK 500', 1, 0, 1),
('WEAPON_PHOENIX210', 'PHOENIX 210 CARRY', 1, 0, 1),
('WEAPON_RAV7', 'RAVEN-7', 1, 0, 1),
('WEAPON_REDARP', 'TRED DRAG ARP', 1, 0, 1),
('WEAPON_REDM4A1', 'RED DRAG M4A1', 1, 0, 1),
('WEAPON_WINRANGE590', 'WINRANGE 590', 1, 0, 1),
('WEAPON_RANGERP40', 'RANGER P40', 1, 0, 1),
('WEAPON_TPATRIOT1911', 'TAN PATRIOT 1911', 1, 0, 1),
('WEAPON_TARP', 'RTAN ARP', 1, 0, 1),
('WEAPON_TT19', 'TAN T19', 1, 0, 1),
('WEAPON_TAC9S', 'TAC 9 W STRAP', 1, 0, 1),
('WEAPON_WOARP', 'WHITE OUT ARP', 1, 0, 1),

('COMPONENT_AT_BAR15_SCOPE_MEDIUM', 'AR 15 Scope', 1, 0, 1),
('COMPONENT_AT_AR_BAR15_FLSH', 'AR 15 Flashlist', 1, 0, 1),
('COMPONENT_AT_AR_BAR15_AFGRIP', 'AR 15 Grip', 1, 0, 1),

('COMPONENT_BLACKSTORM_CLIP_02', 'Black Tommy Extended Clip', 1, 0, 1),

('COMPONENT_BLACKTOMMY_CLIP_02', 'Black Tommy Extended Clip', 1, 0, 1),

('COMPONENT_BLUETITANS_CLIP_02', 'BLUE TITAN SWITCH Extended Clip', 1, 0, 1),
('COMPONENT_BLUETITANS_CLIP_03', 'BLUE TITAN SWITCH Drum mag', 1, 0, 1),
('COMPONENT_BLUETITANS_CLIP_04', 'BLUE TITAN SWITCH 100 Round Mag', 1, 0, 1),
('COMPONENT_BLUETITANS_CLIP_05', 'BLUE TITAN SWITCH Clear Round Mag', 1, 0, 1),

('COMPONENT_AT_DMK18_SCOPE_MEDIUM', 'DESERET MK18 Scope', 1, 0, 1),
('COMPONENT_AT_AR_DMK18_FLSH', 'DESERET MK18 Flashlist', 1, 0, 1),
('COMPONENT_AT_AR_DMK18_AFGRIP', 'DESERET MK18 Grip', 1, 0, 1),
('COMPONENT_AT_AR_DMK18_SUPP', 'DESERET MK18 Suppressor', 1, 0, 1),

('COMPONENT_TITAN41_CLIP_02', 'DESERET MK18 Extended Clip', 1, 0, 1),

('COMPONENT_TITANBEAMS_CLIP_02', 'TITAN BEAM Extended Clip', 1, 0, 1),
('COMPONENT_TITANBEAMS_CLIP_03', 'TITAN BEAM Drum mag', 1, 0, 1),
('COMPONENT_TITANBEAMS_CLIP_04', 'TITAN BEAM 100 Round Mag', 1, 0, 1),
('COMPONENT_TITANBEAMS_CLIP_05', 'TITAN BEAM Clear Round Mag', 1, 0, 1),

('COMPONENT_ILLTITAN17_CLIP_02', 'ILLEGAL TITAN 17 Extended Clip', 1, 0, 1),
('COMPONENT_ILLTITAN17_CLIP_03', 'ILLEGAL TITAN 17 Drum mag', 1, 0, 1),
('COMPONENT_ILLTITAN17_CLIP_04', 'ILLEGAL TITAN 17 100 Round Mag', 1, 0, 1),
('COMPONENT_ILLTITAN17_CLIP_05', 'ILLEGAL TITAN 17 Clear Round Mag', 1, 0, 1),


('COMPONENT_LBTANARP_CLIP_02', 'LB TAN ARP Extended Clip', 1, 0, 1),
('COMPONENT_LBTANARP_CLIP_03', 'LB TAN ARP Drum mag', 1, 0, 1),
('COMPONENT_LBTANARP_CLIP_04', 'LB TAN ARP Clear Round Mag', 1, 0, 1),

('COMPONENT_MGTITAN_CLIP_02', 'MG TITAN Extended Clip', 1, 0, 1),
('COMPONENT_MGTITAN_CLIP_03', 'MG TITAN Drum mag', 1, 0, 1),
('COMPONENT_MGTITAN_CLIP_04', 'MG TITAN 100 Round Mag', 1, 0, 1),
('COMPONENT_MGTITAN_CLIP_05', 'MG TITAN Clear Round Mag', 1, 0, 1),

('COMPONENT_MIDASTITAN_CLIP_02', 'MIDAS TITAN Extended Clip', 1, 0, 1),
('COMPONENT_MIDASTITAN_CLIP_03', 'MIDAS TITAN Drum mag', 1, 0, 1),
('COMPONENT_MIDASTITAN_CLIP_04', 'MIDAS TITAN 100 Round Mag', 1, 0, 1),
('COMPONENT_MIDASTITAN_CLIP_05', 'MIDAS TITAN Clear Round Mag', 1, 0, 1),

('COMPONENT_RAV7_CLIP_02', 'RAV7 Extended Clip', 1, 0, 1),

('COMPONENT_REDARP_CLIP_02', 'RED ARP Extended Clip', 1, 0, 1),
('COMPONENT_REDARP_CLIP_03', 'RED ARP Drum mag', 1, 0, 1),
('COMPONENT_REDARP_CLIP_04', 'RED ARP Clear Round Mag', 1, 0, 1),

('COMPONENT_REDM4A1_CLIP_02', 'RED M4A1 Extended Clip', 1, 0, 1),
('COMPONENT_AT_AR_REDM4A1_SUPP', 'RED M4A1 Suppressor', 1, 0, 1),

('COMPONENT_TANARP_CLIP_02', 'TAN ARP Extended Clip', 1, 0, 1),
('COMPONENT_TANARP_CLIP_03', 'TAN ARP Drum mag', 1, 0, 1),
('COMPONENT_TANARP_CLIP_04', 'TAN ARP Clear Round Mag', 1, 0, 1),

('COMPONENT_TT19_CLIP_02', 'TAN T19 Extended Clip', 1, 0, 1),
('COMPONENT_TT19_CLIP_03', 'TAN T19 Drum mag', 1, 0, 1),
('COMPONENT_TT19_CLIP_04', 'TAN T19 100 Round Mag', 1, 0, 1),
('COMPONENT_TT19_CLIP_05', 'TAN T19 Clear Round Mag', 1, 0, 1),

('COMPONENT_TAC9S_CLIP_02', 'TAC 9 W STRAP Extended Clip', 1, 0, 1),

('COMPONENT_WOARP_CLIP_02', 'WHITE OUT ARP Extended Clip', 1, 0, 1),
('COMPONENT_WOARP_CLIP_03', 'WHITE OUT ARP Drum mag', 1, 0, 1),
('COMPONENT_WOARP_CLIP_04', 'WHITE OUT ARP Clear Round Mag', 1, 0, 1);