INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('invisibility_vape', 'Invisibility Vape', 1, 0, 1),
('speed_vape', 'Speed Vape', 1, 0, 1),
('superjump_vape', 'Super Jump Vape', 1, 0, 1),
('teleport_vape', 'Teleport Vape', 1, 0, 1),
('invincibility_vape', 'Invincibility Vape', 1, 0, 1),
('transform_vape', 'Transform Vape', 1, 0, 1),
('freeze_vape', 'Freeze Vape', 1, 0, 1),
('gravity_vape', 'Gravity Vape', 1, 0, 1),
('health_vape', 'Health Vape', 1, 0, 1),
('armor_vape', 'Armor Vape', 1, 0, 1),
('random_vape', 'Random Vape', 1, 0, 1),
('carspeed_vape', 'Car Speed Vape', 1, 0, 1),
('vape', 'Vape', 1, 0, 1),
('vape_watermelon', 'Watermelon Vape', 1, 0, 1),
('vape_mango', 'Mango Vape', 1, 0, 1),
('vape_blueberry', 'Blueberry Vape', 1, 0, 1),
('vape_strawberry', 'Strawberry Vape', 1, 0, 1),
('vape_pineapple', 'Pineapple Vape', 1, 0, 1),
('vape_grape', 'Grape Vape', 1, 0, 1),
('vape_cherry', 'Cherry Vape', 1, 0, 1),
('vape_lime', 'Lime Vape', 1, 0, 1),
('vape_coconut', 'Coconut Vape', 1, 0, 1),
('vape_raspberry', 'Raspberry Vape', 1, 0, 1),
('vape_peach', 'Peach Vape', 1, 0, 1),
('vape_mint', 'Mint Vape', 1, 0, 1),
('vape_vanilla', 'Vanilla Vape', 1, 0, 1),
('vape_lemon', 'Lemon Vape', 1, 0, 1),
('vape_banana', 'Banana Vape', 1, 0, 1),
('vape_apple', 'Apple Vape', 1, 0, 1),
('vape_kiwi', 'Kiwi Vape', 1, 0, 1),
('vape_caramel', 'Caramel Vape', 1, 0, 1),
('vape_cinnamon', 'Cinnamon Vape', 1, 0, 1),
('vape_honey', 'Honey Vape', 1, 0, 1),
('vape_pear', 'Pear Vape', 1, 0, 1),
('vape_cranberry', 'Cranberry Vape', 1, 0, 1),
('vape_coffee', 'Coffee Vape', 1, 0, 1),
('vape_pomegranate', 'Pomegranate Vape', 1, 0, 1),
('vape_tangerine', 'Tangerine Vape', 1, 0, 1),
('vape_chocolate', 'Chocolate Vape', 1, 0, 1),
('vape_guava', 'Guava Vape', 1, 0, 1),
('vape_toffee', 'Toffee Vape', 1, 0, 1),
('vape_blackberry', 'Blackberry Vape', 1, 0, 1),
('vape_apricot', 'Apricot Vape', 1, 0, 1),
('vape_plum', 'Plum Vape', 1, 0, 1),
('vape_passionfruit', 'Passionfruit Vape', 1, 0, 1),
('vape_lychee', 'Lychee Vape', 1, 0, 1),
('vape_dragonfruit', 'Dragonfruit Vape', 1, 0, 1),
('vape_paella', 'Paella Vape', 1, 0, 1),
('vape_cucumber', 'Cucumber Vape', 1, 0, 1),
('vape_berrymix', 'Berry Mix Vape', 1, 0, 1),
('vape_hazelnut', 'Hazelnut Vape', 1, 0, 1),
('vape_melon', 'Melon Vape', 1, 0, 1),
('vape_ginger', 'Ginger Vape', 1, 0, 1);