local WeaponsRaw = {
    [`weapon_unarmed`]               = { name = 'weapon_unarmed', label = 'Fists'},
    [`weapon_dagger`]                = { name = 'weapon_dagger', label = 'Dagger'},
    [`weapon_bat`]                   = { name = 'weapon_bat', label = 'Bat'},
    [`weapon_bottle`]                = { name = 'weapon_bottle', label = 'Broken Bottle'},
    [`weapon_crowbar`]               = { name = 'weapon_crowbar', label = 'Crowbar'},
    [`weapon_flashlight`]            = { name = 'weapon_flashlight', label = 'Flashlight'},
    [`weapon_golfclub`]              = { name = 'weapon_golfclub', label = 'Golfclub'},
    [`weapon_hammer`]                = { name = 'weapon_hammer', label = 'Hammer'},
    [`weapon_hatchet`]               = { name = 'weapon_hatchet', label = 'Hatchet'},
    [`weapon_knuckle`]               = { name = 'weapon_knuckle', label = 'Knuckle'},
    [`weapon_knife`]                 = { name = 'weapon_knife', label = 'Knife'},
    [`weapon_machete`]               = { name = 'weapon_machete', label = 'Machete'},
    [`weapon_switchblade`]           = { name = 'weapon_switchblade', label = 'Switchblade'},
    [`weapon_nightstick`]            = { name = 'weapon_nightstick', label = 'Nightstick'},
    [`weapon_wrench`]                = { name = 'weapon_wrench', label = 'Wrench'},
    [`weapon_battleaxe`]             = { name = 'weapon_battleaxe', label = 'Battle Axe'},
    [`weapon_poolcue`]               = { name = 'weapon_poolcue', label = 'Poolcue'},
    [`weapon_briefcase`]             = { name = 'weapon_briefcase', label = 'Briefcase'},
    [`weapon_briefcase_02`]          = { name = 'weapon_briefcase_02', label = 'Briefcase'},
    [`weapon_garbagebag`]            = { name = 'weapon_garbagebag', label = 'Garbage Bag'},
    [`weapon_handcuffs`]             = { name = 'weapon_handcuffs', label = 'Handcuffs'},
    [`weapon_bread`]                 = { name = 'weapon_bread', label = 'Baquette'},
    [`weapon_stone_hatchet`]         = { name = 'weapon_stone_hatchet', label = 'Stone Hatchet'},
    [`weapon_candycane`]             = { name = 'weapon_candycane', label = 'Candy Cane' },

    -- Handguns
    [`weapon_pistol`]                = { name = 'weapon_pistol', label = 'Pistol'},
    [`weapon_pistol_mk2`]            = { name = 'weapon_pistol_mk2', label = 'Pistol Mk2'},
    [`weapon_combatpistol`]          = { name = 'weapon_combatpistol', label = 'Combat Pistol'},
    [`weapon_appistol`]              = { name = 'weapon_appistol', label = 'AP Pistol'},
    [`weapon_stungun`]               = { name = 'weapon_stungun', label = 'Taser'},
    [`weapon_pistol50`]              = { name = 'weapon_pistol50', label = 'Pistol .50 Cal'},
    [`weapon_snspistol`]             = { name = 'weapon_snspistol', label = 'SNS Pistol'},
    [`weapon_snspistol_mk2`]         = { name = 'weapon_snspistol_mk2', label = 'SNS Pistol MK2'},
    [`weapon_heavypistol`]           = { name = 'weapon_heavypistol', label = 'Heavy Pistol'},
    [`weapon_vintagepistol`]         = { name = 'weapon_vintagepistol', label = 'Vintage Pistol'},
    [`weapon_flaregun`]              = { name = 'weapon_flaregun', label = 'Flare Gun'},
    [`weapon_marksmanpistol`]        = { name = 'weapon_marksmanpistol', label = 'Marksman Pistol'},
    [`weapon_revolver`]              = { name = 'weapon_revolver', label = 'Revolver'},
    [`weapon_revolver_mk2`]          = { name = 'weapon_revolver_mk2', label = 'Revolver MK2'},
    [`weapon_doubleaction`]          = { name = 'weapon_doubleaction', label = 'Double Action Revolver'},
    [`weapon_raypistol`]             = { name = 'weapon_raypistol', label = 'Ray Pistol'},
    [`weapon_ceramicpistol`]         = { name = 'weapon_ceramicpistol', label = 'Ceramic Pistol'},
    [`weapon_navyrevolver`]          = { name = 'weapon_navyrevolver', label = 'Navy Revolver'},
    [`weapon_gadgetpistol`]          = { name = 'weapon_gadgetpistol', label = 'Gadget Pistol'},

    -- Submachine Guns
    [`weapon_microsmg`]              = { name = 'weapon_microsmg', label = 'Micro SMG'},
    [`weapon_smg`]                   = { name = 'weapon_smg', label = 'SMG'},
    [`weapon_smg_mk2`]               = { name = 'weapon_smg_mk2', label = 'SMG MK2'},
    [`weapon_assaultsmg`]            = { name = 'weapon_assaultsmg', label = 'Assault SMG'},
    [`weapon_combatpdw`]             = { name = 'weapon_combatpdw', label = 'Combat PDW'},
    [`weapon_machinepistol`]         = { name = 'weapon_machinepistol', label = 'Tec-9'},
    [`weapon_minismg`]               = { name = 'weapon_minismg', label = 'Mini SMG'},
    [`weapon_raycarbine`]            = { name = 'weapon_raycarbine', label = 'Raycarbine'},

    -- Shotguns
    [`weapon_pumpshotgun`]           = { name = 'weapon_pumpshotgun', label = 'Pump Shotgun'},
    [`weapon_pumpshotgun_mk2`]       = { name = 'weapon_pumpshotgun_mk2', label = 'Pump Shotgun MK2'},
    [`weapon_sawnoffshotgun`]        = { name = 'weapon_sawnoffshotgun', label = 'Sawn-off Shotgun'},
    [`weapon_assaultshotgun`]        = { name = 'weapon_assaultshotgun', label = 'Assault Shotgun'},
    [`weapon_bullpupshotgun`]        = { name = 'weapon_bullpupshotgun', label = 'Bullpup Shotgun'},
    [`weapon_musket`]                = { name = 'weapon_musket', label = 'Musket'},
    [`weapon_heavyshotgun`]          = { name = 'weapon_heavyshotgun', label = 'Heavy Shotgun'},
    [`weapon_dbshotgun`]             = { name = 'weapon_dbshotgun', label = 'Double-barrel Shotgun'},
    [`weapon_autoshotgun`]           = { name = 'weapon_autoshotgun', label = 'Auto Shotgun'},
    [`weapon_combatshotgun`]         = { name = 'weapon_combatshotgun', label = 'Combat Shotgun'},

    -- Assault Rifles
    [`weapon_assaultrifle`]          = { name = 'weapon_assaultrifle', label = 'Assault Rifle'},
    [`weapon_assaultrifle_mk2`]      = { name = 'weapon_assaultrifle_mk2', label = 'Assault Rifle MK2'},
    [`weapon_carbinerifle`]          = { name = 'weapon_carbinerifle', label = 'Carbine Rifle'},
    [`weapon_carbinerifle_mk2`]      = { name = 'weapon_carbinerifle_mk2', label = 'Carbine Rifle MK2'},
    [`weapon_advancedrifle`]         = { name = 'weapon_advancedrifle', label = 'Advanced Rifle'},
    [`weapon_specialcarbine`]        = { name = 'weapon_specialcarbine', label = 'Special Carbine'},
    [`weapon_specialcarbine_mk2`]    = { name = 'weapon_specialcarbine_mk2', label = 'Specialcarbine MK2'},
    [`weapon_bullpuprifle`]          = { name = 'weapon_bullpuprifle', label = 'Bullpup Rifle'},
    [`weapon_bullpuprifle_mk2`]      = { name = 'weapon_bullpuprifle_mk2', label = 'Bull Puprifle MK2'},
    [`weapon_compactrifle`]          = { name = 'weapon_compactrifle', label = 'Compact Rifle'},
    [`weapon_militaryrifle`]         = { name = 'weapon_militaryrifle', label = 'Military Rifle'},
    [`weapon_heavyrifle`]            = { name = 'weapon_heavyrifle', label = 'Heavy Rifle'},

    -- Light Machine Guns
    [`weapon_mg`]                    = { name = 'weapon_mg', label = 'Machinegun' },
    [`weapon_combatmg`]              = { name = 'weapon_combatmg', label = 'Combat MG' },
    [`weapon_combatmg_mk2`]          = { name = 'weapon_combatmg_mk2', label = 'Combat MG MK2' },
    [`weapon_gusenberg`]             = { name = 'weapon_gusenberg', label = 'Thompson SMG' },

    -- Sniper Rifles
    [`weapon_sniperrifle`]           = { name = 'weapon_sniperrifle', label = 'Sniper Rifle' },
    [`weapon_heavysniper`]           = { name = 'weapon_heavysniper', label = 'Heavy Sniper' },
    [`weapon_heavysniper_mk2`]       = { name = 'weapon_heavysniper_mk2', label = 'Heavysniper MK2' },
    [`weapon_marksmanrifle`]         = { name = 'weapon_marksmanrifle', label = 'Marksman Rifle' },
    [`weapon_marksmanrifle_mk2`]     = { name = 'weapon_marksmanrifle_mk2', label = 'Marksman Rifle MK2' },
    [`weapon_remotesniper`]          = { name = 'weapon_remotesniper', label = 'Remote Sniper' },
    [`weapon_precisionrifle`]        = { name = 'weapon_precisionrifle', label = 'Precision Rifle' },
    [`weapon_tacticalrifle`]         = { name = 'weapon_tacticalrifle', label = 'Tactical Rifle' },

    -- Explosives & Launchers
    [`weapon_rpg`]                   = { name = 'weapon_rpg', label = 'RPG' },
    [`weapon_grenadelauncher`]       = { name = 'weapon_grenadelauncher', label = 'Grenade Launcher' },
    [`weapon_grenadelauncher_smoke`] = { name = 'weapon_grenadelauncher_smoke', label = 'Smoke Grenade Launcher' },
    [`weapon_minigun`]               = { name = 'weapon_minigun', label = 'Minigun' },
    [`weapon_firework`]              = { name = 'weapon_firework', label = 'Firework Launcher' },
    [`weapon_railgun`]               = { name = 'weapon_railgun', label = 'Railgun' },
    [`weapon_hominglauncher`]        = { name = 'weapon_hominglauncher', label = 'Homing Launcher' },
    [`weapon_compactlauncher`]       = { name = 'weapon_compactlauncher', label = 'Compact Launcher' },
    [`weapon_rayminigun`]            = { name = 'weapon_rayminigun', label = 'Ray Minigun' },

    -- Throwables
    [`weapon_grenade`]               = { name = 'weapon_grenade', label = 'Grenade' },
    [`weapon_bzgas`]                 = { name = 'weapon_bzgas', label = 'BZ Gas' },
    [`weapon_molotov`]               = { name = 'weapon_molotov', label = 'Molotov Cocktail' },
    [`weapon_stickybomb`]            = { name = 'weapon_stickybomb', label = 'Sticky Bomb' },
    [`weapon_proxmine`]              = { name = 'weapon_proxmine', label = 'Proximity Mine' },
    [`weapon_snowball`]              = { name = 'weapon_snowball', label = 'Snowball' },
    [`weapon_pipebomb`]              = { name = 'weapon_pipebomb', label = 'Pipe Bomb' },
    [`weapon_ball`]                  = { name = 'weapon_ball', label = 'Ball' },
    [`weapon_smokegrenade`]          = { name = 'weapon_smokegrenade', label = 'Smoke Grenade' },
    [`weapon_flare`]                 = { name = 'weapon_flare', label = 'Flare' },
    [`weapon_petrolcan`]             = { name = 'weapon_petrolcan', label = 'Jerry Can' },
    [`weapon_fireextinguisher`]      = { name = 'weapon_fireextinguisher', label = 'Fire Extinguisher' },
    [`weapon_hazardcan`]             = { name = 'weapon_hazardcan', label = 'Hazard Can' },
    [`weapon_metaldetector`]         = { name = 'weapon_metaldetector', label = 'Metal Detector' },

    -- Custom Melee Weapons - Karambit Variants
    [`weapon_karambit_forest`]       = { name = 'weapon_karambit_forest', label = 'Karambit Forest' },
    [`weapon_karambit_safarimesh`]   = { name = 'weapon_karambit_safarimesh', label = 'Karambit Safari Mesh' },
    [`weapon_karambit_borealforest`] = { name = 'weapon_karambit_borealforest', label = 'Karambit Boreal Forest' },
    [`weapon_karambit_scorched`]     = { name = 'weapon_karambit_scorched', label = 'Karambit Scorched' },
    [`weapon_karambit_urbanmasked`]  = { name = 'weapon_karambit_urbanmasked', label = 'Karambit Urban Masked' },
    [`weapon_karambit_rustcoat`]     = { name = 'weapon_karambit_rustcoat', label = 'Karambit Rust Coat' },
    [`weapon_karambit_night`]        = { name = 'weapon_karambit_night', label = 'Karambit Night' },
    [`weapon_karambit_stained`]      = { name = 'weapon_karambit_stained', label = 'Karambit Stained' },
    [`weapon_karambit_ultraviolet`]  = { name = 'weapon_karambit_ultraviolet', label = 'Karambit Ultraviolet' },
    [`weapon_karambit_brightwater`]  = { name = 'weapon_karambit_brightwater', label = 'Karambit Bright Water' },
    [`weapon_karambit_crimsonweb`]   = { name = 'weapon_karambit_crimsonweb', label = 'Karambit Crimson Web' },
    [`weapon_karambit_freehand`]     = { name = 'weapon_karambit_freehand', label = 'Karambit Freehand' },
    [`weapon_karambit_damascussteel`] = { name = 'weapon_karambit_damascussteel', label = 'Karambit Damascus Steel' },
    [`weapon_karambit_casehardend`]  = { name = 'weapon_karambit_casehardend', label = 'Karambit Case Hardened' },
    [`weapon_karambit_bluesteel`]    = { name = 'weapon_karambit_bluesteel', label = 'Karambit Blue Steel' },
    [`weapon_karambit_lore`]         = { name = 'weapon_karambit_lore', label = 'Karambit Lore' },
    [`weapon_karambit_blacklaminated`] = { name = 'weapon_karambit_blacklaminated', label = 'Karambit Black Laminate' },
    [`weapon_karambit_slaughter`]    = { name = 'weapon_karambit_slaughter', label = 'Karambit Slaughter' },
    [`weapon_karambit_tigertooth`]   = { name = 'weapon_karambit_tigertooth', label = 'Karambit Tiger Tooth' },
    [`weapon_karambit_dopplerphase1`] = { name = 'weapon_karambit_dopplerphase1', label = 'Karambit Doppler Phase 1' },
    [`weapon_karambit_dopplerphase3`] = { name = 'weapon_karambit_dopplerphase3', label = 'Karambit Doppler Phase 3' },
    [`weapon_karambit_autotronic`]   = { name = 'weapon_karambit_autotronic', label = 'Karambit Autotronic' },
    [`weapon_karambit_marblefade`]   = { name = 'weapon_karambit_marblefade', label = 'Karambit Marble Fade' },
    [`weapon_karambit_dopplerphase2`] = { name = 'weapon_karambit_dopplerphase2', label = 'Karambit Doppler Phase 2' },
    [`weapon_karambit_dopplerphase4`] = { name = 'weapon_karambit_dopplerphase4', label = 'Karambit Doppler Phase 4' },
    [`weapon_karambit_gdp1`]         = { name = 'weapon_karambit_gdp1', label = 'Karambit Gamma Doppler Phase 1' },
    [`weapon_karambit_gdp3`]         = { name = 'weapon_karambit_gdp3', label = 'Karambit Gamma Doppler Phase 3' },
    [`weapon_karambit_gdp4`]         = { name = 'weapon_karambit_gdp4', label = 'Karambit Gamma Doppler Phase 4' },
    [`weapon_karambit_fade`]         = { name = 'weapon_karambit_fade', label = 'Karambit Fade' },
    [`weapon_karambit_gdp2`]         = { name = 'weapon_karambit_gdp2', label = 'Karambit Gamma Doppler Phase 2' },
    [`weapon_karambit_blackpearl`]   = { name = 'weapon_karambit_blackpearl', label = 'Karambit Black Pearl' },
    [`weapon_karambit_dopplerruby`]  = { name = 'weapon_karambit_dopplerruby', label = 'Karambit Doppler Ruby' },
    [`weapon_karambit_gdemerald`]    = { name = 'weapon_karambit_gdemerald', label = 'Karambit Gamma Doppler Emerald' },
    [`weapon_karambit_dopplersapphire`] = { name = 'weapon_karambit_dopplersapphire', label = 'Karambit Doppler Sapphire' },

    -- Butterfly Knife Variants
    [`weapon_bf_scorched`]           = { name = 'weapon_bf_scorched', label = 'Butterfly Knife Scorched' },
    [`weapon_bf_safarimesh`]         = { name = 'weapon_bf_safarimesh', label = 'Butterfly Knife Safari Mesh' },
    [`weapon_bf_urbanmasked`]        = { name = 'weapon_bf_urbanmasked', label = 'Butterfly Knife Urban Masked' },
    [`weapon_bf_forest`]             = { name = 'weapon_bf_forest', label = 'Butterfly Knife Forest' },
    [`weapon_bf_borealforest`]       = { name = 'weapon_bf_borealforest', label = 'Butterfly Knife Boreal Forest' },
    [`weapon_bf_ultraviolet`]        = { name = 'weapon_bf_ultraviolet', label = 'Butterfly Knife Ultraviolet' },
    [`weapon_bf_night`]              = { name = 'weapon_bf_night', label = 'Butterfly Knife Night' },
    [`weapon_bf_stained`]            = { name = 'weapon_bf_stained', label = 'Butterfly Knife Stained' },
    [`weapon_bf_rustcoat`]           = { name = 'weapon_bf_rustcoat', label = 'Butterfly Knife Rust Coat' },
    [`weapon_bf_casehardend`]        = { name = 'weapon_bf_casehardend', label = 'Butterfly Knife Case Hardened' },
    [`weapon_bf_bluesteel`]          = { name = 'weapon_bf_bluesteel', label = 'Butterfly Knife Blue Steel' },
    [`weapon_bf_crimsonweb`]         = { name = 'weapon_bf_crimsonweb', label = 'Butterfly Knife Crimson Web' },
    [`weapon_bf_damascussteel`]      = { name = 'weapon_bf_damascussteel', label = 'Butterfly Knife Damascus Steel' },
    [`weapon_bf_slaughter`]          = { name = 'weapon_bf_slaughter', label = 'Butterfly Knife Slaughter' },
    [`weapon_bf_tigertooth`]         = { name = 'weapon_bf_tigertooth', label = 'Butterfly Knife Tiger Tooth' },
    [`weapon_bf_dopplerphase3`]      = { name = 'weapon_bf_dopplerphase3', label = 'Butterfly Knife Doppler Phase 3' },
    [`weapon_bf_dopplerphase1`]      = { name = 'weapon_bf_dopplerphase1', label = 'Butterfly Knife Doppler Phase 1' },
    [`weapon_bf_dopplerphase2`]      = { name = 'weapon_bf_dopplerphase2', label = 'Butterfly Knife Doppler Phase 2' },
    [`weapon_bf_fade`]               = { name = 'weapon_bf_fade', label = 'Butterfly Knife Fade' },
    [`weapon_bf_dopplerphase4`]      = { name = 'weapon_bf_dopplerphase4', label = 'Butterfly Knife Doppler Phase 4' },
    [`weapon_bf_dopplerblackpearl`]  = { name = 'weapon_bf_dopplerblackpearl', label = 'Butterfly Knife Doppler Black Pearl' },
    [`weapon_bf_dopplerruby`]        = { name = 'weapon_bf_dopplerruby', label = 'Butterfly Knife Doppler Ruby' },
    [`weapon_bf_dopplersapphire`]    = { name = 'weapon_bf_dopplersapphire', label = 'Butterfly Knife Doppler Sapphire' },

    -- M9 Bayonet Variants
    [`weapon_m9_safarimesh`]         = { name = 'weapon_m9_safarimesh', label = 'M9 Bayonet Safari Mesh' },
    [`weapon_m9_urbanmasked`]        = { name = 'weapon_m9_urbanmasked', label = 'M9 Bayonet Urban Masked' },
    [`weapon_m9_scorched`]           = { name = 'weapon_m9_scorched', label = 'M9 Bayonet Scorched' },
    [`weapon_m9_stained`]            = { name = 'weapon_m9_stained', label = 'M9 Bayonet Stained' },
    [`weapon_m9_ultraviolet`]        = { name = 'weapon_m9_ultraviolet', label = 'M9 Bayonet Ultraviolet' },
    [`weapon_m9_brightwater`]        = { name = 'weapon_m9_brightwater', label = 'M9 Bayonet Bright Water' },
    [`weapon_m9_crimsonweb`]         = { name = 'weapon_m9_crimsonweb', label = 'M9 Bayonet Crimson Web' },
    [`weapon_m9_freehand`]           = { name = 'weapon_m9_freehand', label = 'M9 Bayonet Freehand' },
    [`weapon_m9_damascussteel`]      = { name = 'weapon_m9_damascussteel', label = 'M9 Bayonet Damascus Steel' },
    [`weapon_m9_casehardend`]        = { name = 'weapon_m9_casehardend', label = 'M9 Bayonet Case Hardened' },
    [`weapon_m9_bluesteel`]          = { name = 'weapon_m9_bluesteel', label = 'M9 Bayonet Blue Steel' },
    [`weapon_m9_lore`]               = { name = 'weapon_m9_lore', label = 'M9 Bayonet Lore' },
    [`weapon_m9_blacklaminate`]      = { name = 'weapon_m9_blacklaminate', label = 'M9 Bayonet Black Laminate' },
    [`weapon_m9_slaughter`]          = { name = 'weapon_m9_slaughter', label = 'M9 Bayonet Slaughter' },
    [`weapon_m9_tigertooth`]         = { name = 'weapon_m9_tigertooth', label = 'M9 Bayonet Tiger Tooth' },
    [`weapon_m9_doppler1`]           = { name = 'weapon_m9_doppler1', label = 'M9 Bayonet Doppler Phase 1' },
    [`weapon_m9_doppler3`]           = { name = 'weapon_m9_doppler3', label = 'M9 Bayonet Doppler Phase 3' },
    [`weapon_m9_autotronic`]         = { name = 'weapon_m9_autotronic', label = 'M9 Bayonet Autotronic' },
    [`weapon_m9_marblefade`]         = { name = 'weapon_m9_marblefade', label = 'M9 Bayonet Marble Fade' },
    [`weapon_m9_doppler2`]           = { name = 'weapon_m9_doppler2', label = 'M9 Bayonet Doppler Phase 2' },
    [`weapon_m9_doppler4`]           = { name = 'weapon_m9_doppler4', label = 'M9 Bayonet Doppler Phase 4' },
    [`weapon_m9_gdp1`]               = { name = 'weapon_m9_gdp1', label = 'M9 Bayonet Gamma Doppler Phase 1' },
    [`weapon_m9_gdp3`]               = { name = 'weapon_m9_gdp3', label = 'M9 Bayonet Gamma Doppler Phase 3' },
    [`weapon_m9_gdp4`]               = { name = 'weapon_m9_gdp4', label = 'M9 Bayonet Gamma Doppler Phase 4' },
    [`weapon_m9_fade`]               = { name = 'weapon_m9_fade', label = 'M9 Bayonet Fade' },
    [`weapon_m9_gdp2`]               = { name = 'weapon_m9_gdp2', label = 'M9 Bayonet Gamma Doppler Phase 2' },
    [`weapon_m9_dopplerblackpearl`]  = { name = 'weapon_m9_dopplerblackpearl', label = 'M9 Bayonet Doppler Black Pearl' },
    [`weapon_m9_dopplerruby`]        = { name = 'weapon_m9_dopplerruby', label = 'M9 Bayonet Doppler Ruby' },
    [`weapon_m9_gdemerald`]          = { name = 'weapon_m9_gdemerald', label = 'M9 Bayonet Gamma Doppler Emerald' },

    -- Custom Weapons
    [`weapon_paintball`]             = { name = 'weapon_paintball', label = 'Paintball Gun' },
    [`weapon_de`]                    = { name = 'weapon_de', label = 'Desert Eagle' },
    [`weapon_ak47m2`]                = { name = 'weapon_ak47m2', label = 'AK-47 M2' },
    [`weapon_hk416`]                 = { name = 'weapon_hk416', label = 'HK416' },
    [`weapon_mp5`]                   = { name = 'weapon_mp5', label = 'MP5' },
    [`weapon_mp5_diamond`]           = { name = 'weapon_mp5_diamond', label = 'MP5 Diamond' },
    [`weapon_m1911`]                 = { name = 'weapon_m1911', label = 'M1911' },
    [`weapon_aa12`]                  = { name = 'weapon_aa12', label = 'AA-12' },
    [`weapon_spas12`]                = { name = 'weapon_spas12', label = 'SPAS-12' },
    [`weapon_m110`]                  = { name = 'weapon_m110', label = 'M110' },
    [`weapon_mk14`]                  = { name = 'weapon_mk14', label = 'MK14' },
    [`weapon_famas`]                 = { name = 'weapon_famas', label = 'FAMAS' },
    [`weapon_uzi`]                   = { name = 'weapon_uzi', label = 'UZI' },
    [`weapon_mac10`]                 = { name = 'weapon_mac10', label = 'MAC-10' },
    [`weapon_m249`]                  = { name = 'weapon_m249', label = 'M249' },
    [`weapon_pkm`]                   = { name = 'weapon_pkm', label = 'PKM' },
    [`weapon_rpd`]                   = { name = 'weapon_rpd', label = 'RPD' },
    [`weapon_huntingrifle`]          = { name = 'weapon_huntingrifle', label = 'Hunting Rifle' },
    [`weapon_crossbow`]              = { name = 'weapon_crossbow', label = 'Crossbow' },
    [`weapon_newspaper`]             = { name = 'weapon_newspaper', label = 'Newspaper' },

    -- KYROS Weapon Pack
    [`weapon_kyros_glock17`]         = { name = 'weapon_kyros_glock17', label = 'Glock 17' },
    [`weapon_kyros_glock18`]         = { name = 'weapon_kyros_glock18', label = 'Glock 18' },
    [`weapon_kyros_glock19`]         = { name = 'weapon_kyros_glock19', label = 'Glock 19' },
    [`weapon_kyros_glock20`]         = { name = 'weapon_kyros_glock20', label = 'Glock 20' },
    [`weapon_kyros_glock22`]         = { name = 'weapon_kyros_glock22', label = 'Glock 22' },
    [`weapon_kyros_ak74`]            = { name = 'weapon_kyros_ak74', label = 'AK-74' },
    [`weapon_kyros_akm`]             = { name = 'weapon_kyros_akm', label = 'AKM' },
    [`weapon_kyros_ak103`]           = { name = 'weapon_kyros_ak103', label = 'AK-103' },
    [`weapon_kyros_ak104`]           = { name = 'weapon_kyros_ak104', label = 'AK-104' },
    [`weapon_kyros_ak105`]           = { name = 'weapon_kyros_ak105', label = 'AK-105' },
    [`weapon_kyros_scarh`]           = { name = 'weapon_kyros_scarh', label = 'SCAR-H' },
    [`weapon_kyros_scarl`]           = { name = 'weapon_kyros_scarl', label = 'SCAR-L' },
    [`weapon_kyros_m4a1`]            = { name = 'weapon_kyros_m4a1', label = 'M4A1' },
    [`weapon_kyros_m16a4`]           = { name = 'weapon_kyros_m16a4', label = 'M16A4' },
    [`weapon_kyros_m16a1`]           = { name = 'weapon_kyros_m16a1', label = 'M16A1' },
    [`weapon_kyros_g36c`]            = { name = 'weapon_kyros_g36c', label = 'G36C' },
    [`weapon_kyros_g36k`]            = { name = 'weapon_kyros_g36k', label = 'G36K' },
    [`weapon_kyros_aug`]             = { name = 'weapon_kyros_aug', label = 'AUG A3' },
    [`weapon_kyros_m14`]             = { name = 'weapon_kyros_m14', label = 'M14' },
    [`weapon_kyros_m24`]             = { name = 'weapon_kyros_m24', label = 'M24 SWS' },
    [`weapon_kyros_awp`]             = { name = 'weapon_kyros_awp', label = 'AWP' },
    [`weapon_kyros_m40a5`]           = { name = 'weapon_kyros_m40a5', label = 'M40A5' },
    [`weapon_kyros_msr`]             = { name = 'weapon_kyros_msr', label = 'MSR' },
    [`weapon_kyros_mp7`]             = { name = 'weapon_kyros_mp7', label = 'MP7' },
    [`weapon_kyros_mp9`]             = { name = 'weapon_kyros_mp9', label = 'MP9' },
    [`weapon_kyros_p90`]             = { name = 'weapon_kyros_p90', label = 'P90' },
    [`weapon_kyros_vector`]          = { name = 'weapon_kyros_vector', label = 'Vector .45 ACP' },
    [`weapon_kyros_pp19`]            = { name = 'weapon_kyros_pp19', label = 'PP-19 Bizon' },
    [`weapon_kyros_pp2000`]          = { name = 'weapon_kyros_pp2000', label = 'PP-2000' },
    [`weapon_kyros_870`]             = { name = 'weapon_kyros_870', label = 'Remington 870' },
    [`weapon_kyros_m1014`]           = { name = 'weapon_kyros_m1014', label = 'M1014' },
    [`weapon_kyros_mk18`]            = { name = 'weapon_kyros_mk18', label = 'MK18' },
    [`weapon_kyros_qbz95`]           = { name = 'weapon_kyros_qbz95', label = 'QBZ-95' },
    [`weapon_kyros_groza`]           = { name = 'weapon_kyros_groza', label = 'Groza' },
    [`weapon_kyros_vss`]             = { name = 'weapon_kyros_vss', label = 'VSS Vintorez' },
    [`weapon_kyros_asval`]           = { name = 'weapon_kyros_asval', label = 'AS Val' },
    [`weapon_kyros_sr25`]            = { name = 'weapon_kyros_sr25', label = 'SR-25' },
    [`weapon_kyros_mk47`]            = { name = 'weapon_kyros_mk47', label = 'MK47 Mutant' },
    [`weapon_kyros_mk17`]            = { name = 'weapon_kyros_mk17', label = 'MK17' },
    [`weapon_kyros_fal`]             = { name = 'weapon_kyros_fal', label = 'FAL' },
    [`weapon_kyros_sa58`]            = { name = 'weapon_kyros_sa58', label = 'SA-58' },
    [`weapon_kyros_sig556`]          = { name = 'weapon_kyros_sig556', label = 'SIG 556' },
    [`weapon_kyros_ace52`]           = { name = 'weapon_kyros_ace52', label = 'ACE 52' },
    [`weapon_kyros_ace23`]           = { name = 'weapon_kyros_ace23', label = 'ACE 23' },
    [`weapon_kyros_p226`]            = { name = 'weapon_kyros_p226', label = 'P226' },
    [`weapon_kyros_p229`]            = { name = 'weapon_kyros_p229', label = 'P229' },
    [`weapon_kyros_p320`]            = { name = 'weapon_kyros_p320', label = 'P320' },
    [`weapon_kyros_usp`]             = { name = 'weapon_kyros_usp', label = 'USP .45' },
    [`weapon_kyros_fnp45`]           = { name = 'weapon_kyros_fnp45', label = 'FNP-45' },
    [`weapon_kyros_m9beretta`]       = { name = 'weapon_kyros_m9beretta', label = 'M9 Beretta' },
    [`weapon_kyros_1911`]            = { name = 'weapon_kyros_1911', label = '1911' },
    [`weapon_kyros_deagle`]          = { name = 'weapon_kyros_deagle', label = 'Desert Eagle' },
    [`weapon_kyros_revolver357`]     = { name = 'weapon_kyros_revolver357', label = '.357 Revolver' },
    [`weapon_kyros_revolver44`]      = { name = 'weapon_kyros_revolver44', label = '.44 Revolver' },
    [`weapon_kyros_berettamx4`]      = { name = 'weapon_kyros_berettamx4', label = 'Beretta MX4' },
    [`weapon_kyros_cz75`]            = { name = 'weapon_kyros_cz75', label = 'CZ75' },
    [`weapon_kyros_tec9`]            = { name = 'weapon_kyros_tec9', label = 'TEC-9' },
    [`weapon_kyros_browninghp`]      = { name = 'weapon_kyros_browninghp', label = 'Browning HP' },
    [`weapon_kyros_makarov`]         = { name = 'weapon_kyros_makarov', label = 'Makarov' },
    [`weapon_kyros_fn57`]            = { name = 'weapon_kyros_fn57', label = 'FN Five-Seven' },
    [`weapon_kyros_czscorpion`]      = { name = 'weapon_kyros_czscorpion', label = 'CZ Scorpion' },
    [`weapon_kyros_thompson`]        = { name = 'weapon_kyros_thompson', label = 'Thompson' },
    [`weapon_kyros_sten`]            = { name = 'weapon_kyros_sten', label = 'STEN' },
    [`weapon_kyros_ppsh41`]          = { name = 'weapon_kyros_ppsh41', label = 'PPSH-41' },
    [`weapon_kyros_mp40`]            = { name = 'weapon_kyros_mp40', label = 'MP40' },
    [`weapon_kyros_m1garand`]        = { name = 'weapon_kyros_m1garand', label = 'M1 Garand' },
    [`weapon_kyros_kar98k`]          = { name = 'weapon_kyros_kar98k', label = 'Kar98k' },
    [`weapon_kyros_mosin`]           = { name = 'weapon_kyros_mosin', label = 'Mosin Nagant' },
    [`weapon_kyros_springfield`]     = { name = 'weapon_kyros_springfield', label = 'Springfield' },
    [`weapon_kyros_barretm82`]       = { name = 'weapon_kyros_barretm82', label = 'Barrett M82' },
    [`weapon_kyros_barretm107`]      = { name = 'weapon_kyros_barretm107', label = 'Barrett M107' },
    [`weapon_kyros_cheytac`]         = { name = 'weapon_kyros_cheytac', label = 'CheyTac M200' },
    [`weapon_kyros_intervention`]    = { name = 'weapon_kyros_intervention', label = 'Intervention' },
    [`weapon_kyros_dragunov`]        = { name = 'weapon_kyros_dragunov', label = 'Dragunov SVD' },
    [`weapon_kyros_t5000`]           = { name = 'weapon_kyros_t5000', label = 'T5000' },
    [`weapon_kyros_rpk`]             = { name = 'weapon_kyros_rpk', label = 'RPK' },
    [`weapon_kyros_pkp`]             = { name = 'weapon_kyros_pkp', label = 'PKP Pecheneg' },
    [`weapon_kyros_mg42`]            = { name = 'weapon_kyros_mg42', label = 'MG42' },
    [`weapon_kyros_mg3`]             = { name = 'weapon_kyros_mg3', label = 'MG3' },
    [`weapon_kyros_m60`]             = { name = 'weapon_kyros_m60', label = 'M60' },
    [`weapon_kyros_mk48`]            = { name = 'weapon_kyros_mk48', label = 'MK48' },
    [`weapon_kyros_l86`]             = { name = 'weapon_kyros_l86', label = 'L86 LSW' },
    [`weapon_kyros_m240`]            = { name = 'weapon_kyros_m240', label = 'M240' },
    [`weapon_kyros_negev`]           = { name = 'weapon_kyros_negev', label = 'Negev' },

    -- Kyros Weapon Pack V5
    [`weapon_bar15`]                 = { name = 'weapon_bar15', label = 'PD AR-15' },
    [`weapon_blackarp`]               = { name = 'weapon_blackarp', label = 'BLACK ARP' },
    [`weapon_bscar`]                 = { name = 'weapon_bscar', label = 'BLACK SCAR' },
    [`weapon_thompson`]              = { name = 'weapon_thompson', label = 'BLACK THOMPSON' },
    [`weapon_dmk18`]                 = { name = 'weapon_dmk18', label = 'PD DESERET MK18' },
    [`weapon_lbtarp`]                = { name = 'weapon_lbtarp', label = 'PD LB TAN ARP' },
    [`weapon_ram7`]                  = { name = 'weapon_ram7', label = 'RAM-7' },
    [`weapon_redarp`]                = { name = 'weapon_redarp', label = 'RED DRAG ARP' },
    [`weapon_redm4a1`]               = { name = 'weapon_redm4a1', label = 'RED DRAG M4A1' },
    [`weapon_tarp`]                  = { name = 'weapon_tarp', label = 'TAN ARP' },
    [`weapon_woarp`]                 = { name = 'weapon_woarp', label = 'WHITE OUT ARP' },
    [`weapon_blueglocks`]            = { name = 'weapon_blueglocks', label = 'BLUE GLOCK SWITCH' },
    [`weapon_fn57`]                  = { name = 'weapon_fn57', label = 'PD FN Five-seveN' },
    [`weapon_glock21`]               = { name = 'weapon_glock21', label = 'PD GLOCK 21' },
    [`weapon_glock41`]               = { name = 'weapon_glock41', label = 'GLOCK 41' },
    [`weapon_glockbeams`]            = { name = 'weapon_glockbeams', label = 'GLOCK BEAM SWITCH' },
    [`weapon_p30l`]                  = { name = 'weapon_p30l', label = 'H&K P30L' },
    [`weapon_illglock17`]            = { name = 'weapon_illglock17', label = 'PD GLOCK 17' },
    [`weapon_mgglock`]               = { name = 'weapon_mgglock', label = 'MG GLOCK' },
    [`weapon_midasglock`]            = { name = 'weapon_midasglock', label = 'MIDAS GLOCK' },
    [`weapon_p210`]                  = { name = 'weapon_p210', label = 'P210 CARRY' },
    [`weapon_sr40`]                  = { name = 'weapon_sr40', label = 'RUGER SR40' },
    [`weapon_t1911`]                 = { name = 'weapon_t1911', label = 'TAN 1911' },
    [`weapon_tglock19`]              = { name = 'weapon_tglock19', label = 'TAN G19' },
    [`weapon_axe`]                   = { name = 'weapon_axe', label = 'AXE' },
    [`weapon_chair`]                 = { name = 'weapon_chair', label = 'BRAWL CHAIR' },
    [`weapon_krissvector`]           = { name = 'weapon_krissvector', label = 'KRISS VECTOR' },
    [`weapon_tec9s`]                 = { name = 'weapon_tec9s', label = 'TEC 9 W STRAP' },
    [`weapon_m500`]                  = { name = 'weapon_m500', label = 'MOSSBERG 500' },
    [`weapon_r590`]                  = { name = 'weapon_r590', label = 'REMINGTON 590' },

    --Custom Guns
    [`weapon_ar15hw`]                = { name = 'weapon_ar15hw', label = 'AR15 HALLOWEEN' },
    [`weapon_toym16`]               = { name = 'weapon_toym16', label = 'TOY GUN M16' },
    [`weapon_saiga9`]               = { name = 'weapon_saiga9', label = 'SAIGA 9' },
    [`weapon_patchday_pistol`]     = { name = 'weapon_patchday_pistol', label = 'PATCHDAY PISTOL' },
    [`weapon_m4a1dragon`]               = { name = 'weapon_m4a1dragon', label = 'DRAGON M4' },
    [`weapon_sabresword`]               = { name = 'weapon_sabresword', label = 'PIRATE SWORD' },
    [`weapon_blue_carbine_rifle`]       = { name = 'weapon_blue_carbine_rifle', label = 'BLUE CARBINE' },
    [`weapon_ultra_blackout_rifle`]     = { name = 'weapon_ultra_blackout_rifle', label = 'BLACKOUT RIFLE' },
    [`weapon_lime_black_ar`]            = { name = 'weapon_lime_black_ar', label = 'LIME BLACK AR' },
    [`weapon_no_silver_rifle`]          = { name = 'weapon_no_silver_rifle', label = 'NO SILVER RIFLE' },
    [`weapon_white_black_ar`]           = { name = 'weapon_white_black_ar', label = 'WHITE AND BLACK AR' },
    [`weapon_white_orange_rifle`]       = { name = 'weapon_white_orange_rifle', label = 'WHITE AND ORANGE RIFLE' },
    [`weapon_candy_apple_glock`]        = { name = 'weapon_candy_apple_glock', label = 'CANDY APPLE GLOCK' },
    [`weapon_catacombs_glock`]          = { name = 'weapon_catacombs_glock', label = 'CATACOMBS GLOCK' },
    [`weapon_freedom_glock`]            = { name = 'weapon_freedom_glock', label = 'FREEDOM GLOCK' },
    [`weapon_hornet_glock`]             = { name = 'weapon_hornet_glock', label = 'HORNET GLOCK' },
    [`weapon_safari_glock`]             = { name = 'weapon_safari_glock', label = 'SAFARI GLOCK' },
    [`weapon_cyan_thermal_katana`]      = { name = 'weapon_cyan_thermal_katana', label = 'CYAN THERMAL KATANA' },
    [`weapon_lime_thermal_katana`]      = { name = 'weapon_lime_thermal_katana', label = 'LIME THERMAL KATANA' },
    [`weapon_pink_thermal_katana`]      = { name = 'weapon_pink_thermal_katana', label = 'PINK THERMAL KATANA' },
    [`weapon_purple_thermal_katana`]    = { name = 'weapon_purple_thermal_katana', label = 'PURPLE THERMAL KATANA' },
    [`weapon_red_thermal_katana`]       = { name = 'weapon_red_thermal_katana', label = 'RED THERMAL KATANA' },
    [`weapon_white_thermal_katana`]     = { name = 'weapon_white_thermal_katana', label = 'WHITE THERMAL KATANA' },
    [`weapon_yellow_thermal_katana`]    = { name = 'weapon_yellow_thermal_katana', label = 'YELLOW THERMAL KATANA' },
    [`weapon_bombinglr300`]             = { name = 'weapon_bombinglr300', label = 'BOMBING LR300' },
    [`weapon_families_glock_18c`]       = { name = 'weapon_families_glock_18c', label = 'FAMILIES GLOCK 18C' },
    [`weapon_hypebeast`]               = { name = 'weapon_hypebeast', label = 'HYPEBEAST' },
    [`weapon_paint_splatter`]          = { name = 'weapon_paint_splatter', label = 'PAINT SPLATTER' },
    [`weapon_pi_revolver`]             = { name = 'weapon_pi_revolver', label = 'PI REVOLVER' },
    [`weapon_reaper_machete`]          = { name = 'weapon_reaper_machete', label = 'REAPER MACHETE' },

    -- Assets Weapons Pack - Assault Rifles
    [`weapon_ak47`]                  = { name = 'weapon_ak47', label = 'AK-47' },
    [`weapon_ak47m2`]                = { name = 'weapon_ak47m2', label = 'AK-47 M2' },
    [`weapon_ak74`]                  = { name = 'weapon_ak74', label = 'AK-74' },
    [`weapon_aks74`]                 = { name = 'weapon_aks74', label = 'AKS-74' },
    [`weapon_ar15`]                  = { name = 'weapon_ar15', label = 'AR-15' },
    [`weapon_ar16`]                  = { name = 'weapon_ar16', label = 'AR-16' },
    [`weapon_fnfal`]                 = { name = 'weapon_fnfal', label = 'FN FAL' },
    [`weapon_scarh`]                 = { name = 'weapon_scarh', label = 'SCAR-H' },
    [`weapon_tar21`]                 = { name = 'weapon_tar21', label = 'TAR-21' },
    [`weapon_pdm4a1`]                = { name = 'weapon_pdm4a1', label = 'PDM M4A1' },

    -- Assets Weapons Pack - Pistols
    [`weapon_browning`]              = { name = 'weapon_browning', label = 'Browning' },
    [`weapon_dp9`]                   = { name = 'weapon_dp9', label = 'DP9' },
    [`weapon_fnfnx45`]               = { name = 'weapon_fnfnx45', label = 'FN FNX-45' },
    [`weapon_glock17`]               = { name = 'weapon_glock17', label = 'Glock 17' },
    [`weapon_glock20`]               = { name = 'weapon_glock20', label = 'Glock 20' },
    [`weapon_glock22`]               = { name = 'weapon_glock22', label = 'Glock 22' },
    [`weapon_m9a3`]                  = { name = 'weapon_m9a3', label = 'M9A3' },
    [`weapon_m45a1`]                 = { name = 'weapon_m45a1', label = 'M45A1' },
    [`weapon_manurhin`]              = { name = 'weapon_manurhin', label = 'Manurhin' },
    [`weapon_python`]                = { name = 'weapon_python', label = 'Python' },
    [`weapon_ragingbull`]            = { name = 'weapon_ragingbull', label = 'Raging Bull' },

    -- Assets Weapons Pack - Submachine Guns
    [`weapon_draco`]                 = { name = 'weapon_draco', label = 'Draco' },
    [`weapon_mp9`]                   = { name = 'weapon_mp9', label = 'MP9' },

    -- Assets Weapons Pack - Shotguns
    [`weapon_komrad12`]              = { name = 'weapon_komrad12', label = 'Komrad 12' },
    [`weapon_mossberg500`]           = { name = 'weapon_mossberg500', label = 'Mossberg 500' },
    [`weapon_remington870`]          = { name = 'weapon_remington870', label = 'Remington 870' },
    [`weapon_saiga12g`]              = { name = 'weapon_saiga12g', label = 'Saiga 12G' },

    -- Assets Weapons Pack - Machine Guns
    [`weapon_m249_mk2`]              = { name = 'weapon_m249_mk2', label = 'M249 MK2' },
    [`weapon_rpd2`]                  = { name = 'weapon_rpd2', label = 'RPD2' },

    -- Assets Weapons Pack - Melee Weapons
    [`weapon_katana`]                = { name = 'weapon_katana', label = 'Katana' },
    [`weapon_keyboard`]               = { name = 'weapon_keyboard', label = 'Keyboard' },
    [`weapon_khukuri`]               = { name = 'weapon_khukuri', label = 'Khukuri' },
    [`weapon_krambit`]               = { name = 'weapon_krambit', label = 'Krambit' },
    [`weapon_penetrator`]            = { name = 'weapon_penetrator', label = 'Penetrator' },
    [`weapon_pick`]                  = { name = 'weapon_pick', label = 'Pickaxe' },
    [`weapon_riftedge`]              = { name = 'weapon_riftedge', label = 'Rift Edge' },
    [`weapon_shiv`]                  = { name = 'weapon_shiv', label = 'Shiv' },
    [`weapon_sledgehammer`]          = { name = 'weapon_sledgehammer', label = 'Sledgehammer' },
    [`weapon_steel_mace`]            = { name = 'weapon_steel_mace', label = 'Steel Mace' },
    [`weapon_sword`]                 = { name = 'weapon_sword', label = 'Sword' },
    [`weapon_berserker`]             = { name = 'weapon_berserker', label = 'Berserker' },
    [`weapon_dildo`]                 = { name = 'weapon_dildo', label = 'Dildo' },

    -- Assets Weapons Pack - Grenades
    [`weapon_m67`]                   = { name = 'weapon_m67', label = 'M67 Grenade' },
    [`weapon_flashbang`]             = { name = 'weapon_flashbang', label = 'Flashbang' },

    -- Assets Weapons Pack - Special
    [`weapon_bdhg`]                  = { name = 'weapon_bdhg', label = 'BDHG' },

    -- CS:GO Knives Pack - M9 Bayonet Variants (Additional)
    [`weapon_m9_dopplerp1`]         = { name = 'weapon_m9_dopplerp1', label = 'M9 Bayonet Doppler Phase 1' },
    [`weapon_m9_dopplerp2`]         = { name = 'weapon_m9_dopplerp2', label = 'M9 Bayonet Doppler Phase 2' },
    [`weapon_m9_dopplerp3`]         = { name = 'weapon_m9_dopplerp3', label = 'M9 Bayonet Doppler Phase 3' },
    [`weapon_m9_dopplerp4`]         = { name = 'weapon_m9_dopplerp4', label = 'M9 Bayonet Doppler Phase 4' },
    [`weapon_m9_slaugther`]         = { name = 'weapon_m9_slaugther', label = 'M9 Bayonet Slaugther' },

    -- CS:GO Knives Pack - Butterfly Knife Variants (Additional)
    [`weapon_bf_dopplerphase1`]     = { name = 'weapon_bf_dopplerphase1', label = 'Butterfly Doppler Phase 1' },
    [`weapon_bf_dopplerphase2`]     = { name = 'weapon_bf_dopplerphase2', label = 'Butterfly Doppler Phase 2' },
    [`weapon_bf_dopplerphase3`]     = { name = 'weapon_bf_dopplerphase3', label = 'Butterfly Doppler Phase 3' },
    [`weapon_bf_dopplerphase4`]     = { name = 'weapon_bf_dopplerphase4', label = 'Butterfly Doppler Phase 4' },
    [`weapon_bf_slaugther`]         = { name = 'weapon_bf_slaugther', label = 'Butterfly Slaugther' },

    -- CS:GO Knives Pack - Karambit Variants (Additional)
    [`weapon_karambit_dopplerblackpearl`] = { name = 'weapon_karambit_dopplerblackpearl', label = 'Karambit Doppler BlackPearl' },
    [`weapon_karambit_dopplerphase1`] = { name = 'weapon_karambit_dopplerphase1', label = 'Karambit Doppler Phase 1' },
    [`weapon_karambit_dopplerphase2`] = { name = 'weapon_karambit_dopplerphase2', label = 'Karambit Doppler Phase 2' },
    [`weapon_karambit_dopplerphase3`] = { name = 'weapon_karambit_dopplerphase3', label = 'Karambit Doppler Phase 3' },
    [`weapon_karambit_dopplerphase4`] = { name = 'weapon_karambit_dopplerphase4', label = 'Karambit Doppler Phase 4' },
    [`weapon_karambit_slaugther`]    = { name = 'weapon_karambit_slaugther', label = 'Karambit Slaugther' },
    [`weapon_karambit_blacklaminate`] = { name = 'weapon_karambit_blacklaminate', label = 'Karambit Black Laminate' },
    [`weapon_karambit_autotronic`]    = { name = 'weapon_karambit_autotronic', label = 'Karambit Autotronic' },
    [`weapon_karambit_freehand`]      = { name = 'weapon_karambit_freehand', label = 'Karambit Free Hand' },
    [`weapon_karambit_gdemerald`]     = { name = 'weapon_karambit_gdemerald', label = 'Karambit Gamma Doppler Emerald' },
    [`weapon_karambit_gdp1`]          = { name = 'weapon_karambit_gdp1', label = 'Karambit Gamma Doppler Phase 1' },
    [`weapon_karambit_gdp2`]          = { name = 'weapon_karambit_gdp2', label = 'Karambit Gamma Doppler Phase 2' },
    [`weapon_karambit_gdp3`]          = { name = 'weapon_karambit_gdp3', label = 'Karambit Gamma Doppler Phase 3' },
    [`weapon_karambit_gdp4`]          = { name = 'weapon_karambit_gdp4', label = 'Karambit Gamma Doppler Phase 4' },
    [`weapon_karambit_lore`]          = { name = 'weapon_karambit_lore', label = 'Karambit Lore' },
    [`weapon_karambit_marblefade`]    = { name = 'weapon_karambit_marblefade', label = 'Karambit Marble Fade' },
    [`weapon_karambit_night`]         = { name = 'weapon_karambit_night', label = 'Karambit Night' },
    [`weapon_karambit_rustcoat`]      = { name = 'weapon_karambit_rustcoat', label = 'Karambit Rust Coat' },
    [`weapon_karambit_safarimesh`]    = { name = 'weapon_karambit_safarimesh', label = 'Karambit Safari Mesh' },
    [`weapon_karambit_scorched`]      = { name = 'weapon_karambit_scorched', label = 'Karambit Scorched' },
    [`weapon_karambit_stained`]       = { name = 'weapon_karambit_stained', label = 'Karambit Stained' },
    [`weapon_karambit_tigertooth`]    = { name = 'weapon_karambit_tigertooth', label = 'Karambit Tiger Tooth' },
    [`weapon_karambit_ultraviolet`]   = { name = 'weapon_karambit_ultraviolet', label = 'Karambit Ultra Violet' },
    [`weapon_karambit_urbanmasked`]   = { name = 'weapon_karambit_urbanmasked', label = 'Karambit Urban Masked' },
    [`weapon_karambit_borealforest`]  = { name = 'weapon_karambit_borealforest', label = 'Karambit Boreal Forest' },
    [`weapon_karambit_brightwater`]   = { name = 'weapon_karambit_brightwater', label = 'Karambit Bright Water' },
    [`weapon_karambit_casehardened`]  = { name = 'weapon_karambit_casehardened', label = 'Karambit Case Hardened' },
    [`weapon_karambit_crimsonweb`]    = { name = 'weapon_karambit_crimsonweb', label = 'Karambit Crimson Web' },
    [`weapon_karambit_damascussteel`] = { name = 'weapon_karambit_damascussteel', label = 'Karambit Damascus Steel' },
    [`weapon_karambit_fade`]          = { name = 'weapon_karambit_fade', label = 'Karambit Fade' },
    [`weapon_karambit_forest`]        = { name = 'weapon_karambit_forest', label = 'Karambit Forest' },
    [`weapon_karambit_dopplerruby`]   = { name = 'weapon_karambit_dopplerruby', label = 'Karambit Doppler Ruby' },
    [`weapon_karambit_dopplersapphire`] = { name = 'weapon_karambit_dopplersapphire', label = 'Karambit Doppler Sapphire' },

    -- CS:GO Knives Pack - M9 Bayonet Variants (Additional - exact names from items.lua)
    [`weapon_m9_autotronic`]           = { name = 'weapon_m9_autotronic', label = 'M9 Bayonet Autotronic' },
    [`weapon_m9_blacklaminate`]        = { name = 'weapon_m9_blacklaminate', label = 'M9 Bayonet Black Laminate' },
    [`weapon_m9_bluesteel`]            = { name = 'weapon_m9_bluesteel', label = 'M9 Bayonet Blue Steel' },
    [`weapon_m9_brightwater`]          = { name = 'weapon_m9_brightwater', label = 'M9 Bayonet Bright Water' },
    [`weapon_m9_casehardened`]         = { name = 'weapon_m9_casehardened', label = 'M9 Bayonet Case Hardened' },
    [`weapon_m9_crimsonweb`]           = { name = 'weapon_m9_crimsonweb', label = 'M9 Bayonet Crimson Web' },
    [`weapon_m9_damascussteel`]       = { name = 'weapon_m9_damascussteel', label = 'M9 Bayonet Damascus Steel' },
    [`weapon_m9_dopplerblackpearl`]    = { name = 'weapon_m9_dopplerblackpearl', label = 'M9 Bayonet Doppler Black Pearl' },
    [`weapon_m9_dopplerruby`]          = { name = 'weapon_m9_dopplerruby', label = 'M9 Bayonet Doppler Ruby' },
    [`weapon_m9_dopplersapphire`]      = { name = 'weapon_m9_dopplersapphire', label = 'M9 Bayonet Doppler Sapphire' },
    [`weapon_m9_gdemerald`]            = { name = 'weapon_m9_gdemerald', label = 'M9 Bayonet Emerald' },
    [`weapon_m9_fade`]                 = { name = 'weapon_m9_fade', label = 'M9 Bayonet Fade' },
    [`weapon_m9_freehand`]             = { name = 'weapon_m9_freehand', label = 'M9 Bayonet Free Hand' },
    [`weapon_m9_gdp1`]                 = { name = 'weapon_m9_gdp1', label = 'M9 Bayonet Gamma Doppler Phase 1' },
    [`weapon_m9_gdp2`]                 = { name = 'weapon_m9_gdp2', label = 'M9 Bayonet Gamma Doppler Phase 2' },
    [`weapon_m9_gdp3`]                 = { name = 'weapon_m9_gdp3', label = 'M9 Bayonet Gamma Doppler Phase 3' },
    [`weapon_m9_gdp4`]                 = { name = 'weapon_m9_gdp4', label = 'M9 Bayonet Gamma Doppler Phase 4' },
    [`weapon_m9_lore`]                 = { name = 'weapon_m9_lore', label = 'M9 Bayonet Lore' },
    [`weapon_m9_marblefade`]           = { name = 'weapon_m9_marblefade', label = 'M9 Bayonet Marble Fade' },
    [`weapon_m9_safarimesh`]           = { name = 'weapon_m9_safarimesh', label = 'M9 Bayonet Safari Mesh' },
    [`weapon_m9_scorched`]             = { name = 'weapon_m9_scorched', label = 'M9 Bayonet Scorched' },
    [`weapon_m9_stained`]               = { name = 'weapon_m9_stained', label = 'M9 Bayonet Stained' },
    [`weapon_m9_tigertooth`]            = { name = 'weapon_m9_tigertooth', label = 'M9 Bayonet Tiger Tooth' },
    [`weapon_m9_ultraviolet`]          = { name = 'weapon_m9_ultraviolet', label = 'M9 Bayonet Ultra Violet' },
    [`weapon_m9_urbanmasked`]          = { name = 'weapon_m9_urbanmasked', label = 'M9 Bayonet Urban Masked' },

    -- CS:GO Knives Pack - Butterfly Knife Variants (Additional - exact names from items.lua)
    [`weapon_bf_bluesteel`]            = { name = 'weapon_bf_bluesteel', label = 'Butterfly Blue Steel' },
    [`weapon_bf_borealforest`]        = { name = 'weapon_bf_borealforest', label = 'Butterfly Boreal Forest' },
    [`weapon_bf_casehardened`]         = { name = 'weapon_bf_casehardened', label = 'Butterfly Case Hardened' },
    [`weapon_bf_crimsonweb`]           = { name = 'weapon_bf_crimsonweb', label = 'Butterfly Crimson Web' },
    [`weapon_bf_damascussteel`]        = { name = 'weapon_bf_damascussteel', label = 'Butterfly Damascus Steel' },
    [`weapon_bf_dopplerblackpearl`]    = { name = 'weapon_bf_dopplerblackpearl', label = 'Butterfly Doppler Black Pearl' },
    [`weapon_bf_dopplerruby`]          = { name = 'weapon_bf_dopplerruby', label = 'Butterfly Doppler Ruby' },
    [`weapon_bf_dopplersapphire`]      = { name = 'weapon_bf_dopplersapphire', label = 'Butterfly Doppler Sapphire' },
    [`weapon_bf_fade`]                 = { name = 'weapon_bf_fade', label = 'Butterfly Fade' },
    [`weapon_bf_forest`]               = { name = 'weapon_bf_forest', label = 'Butterfly Forest' },
    [`weapon_bf_night`]                 = { name = 'weapon_bf_night', label = 'Butterfly Night' },
    [`weapon_bf_rustcoat`]             = { name = 'weapon_bf_rustcoat', label = 'Butterfly Rust Coat' },
    [`weapon_bf_safarimesh`]           = { name = 'weapon_bf_safarimesh', label = 'Butterfly Safari Mesh' },
    [`weapon_bf_scorched`]             = { name = 'weapon_bf_scorched', label = 'Butterfly Scorched' },
    [`weapon_bf_stained`]              = { name = 'weapon_bf_stained', label = 'Butterfly Stained' },
    [`weapon_bf_tigertooth`]           = { name = 'weapon_bf_tigertooth', label = 'Butterfly Tiger Tooth' },
    [`weapon_bf_ultraviolet`]          = { name = 'weapon_bf_ultraviolet', label = 'Butterfly Ultra Violet' },
    [`weapon_bf_urbanmasked`]          = { name = 'weapon_bf_urbanmasked', label = 'Butterfly Urban Masked' },
}

-- Metatable ile hem hash hem de string erişimini destekle
Weapons = setmetatable({}, {
    __index = function(tbl, key)
        -- Eğer key zaten bir hash ise (number), direkt kullan
        if type(key) == 'number' then
            return WeaponsRaw[key]
        end

        -- Eğer key string ise, önce hash'e çevir
        if type(key) == 'string' then
            local hash = GetHashKey(key)
            return WeaponsRaw[hash]
        end

        return nil
    end,

    __newindex = function(tbl, key, value)
        -- Yeni silah eklenirken hem hash hem string ile erişilebilir
        if type(key) == 'string' then
            WeaponsRaw[GetHashKey(key)] = value
        else
            WeaponsRaw[key] = value
        end
    end,

    __pairs = function(tbl)
        -- pairs() ile iterasyon yaparken WeaponsRaw'ı kullan
        return pairs(WeaponsRaw)
    end
})