export const defaultSettings = {
  defaultPositions: {
    server: { x: 0, y: 0 },
    menu: { x: 0, y: 0 },
    status: { x: 0, y: 0 },
    speedo: { x: 0, y: 0 },
    caps: { x: 16, y: 600 },
    health: { x: 16, y: 500 },
    hunger: { x: 80, y: 500 },
    thirst: { x: 144, y: 500 },
    armor: { x: 208, y: 500 },
    energy: { x: 272, y: 500 },
    stress: { x: 336, y: 500 },
    oxygen: { x: 400, y: 500 },
  },
  language: {
    generalSettings: "General Settings",
    statusSettings: "Status Settings",
    serverInfoSettings: "Server Info Settings",
    speedometers: "Speedometers",
    cinematicMode: "Cinematic Mode",
    showLocation: "Show Location",
    minimap: "Minimap",
    freeformEditMode: "Freeform Edit Mode",
    hideAllHud: "Hide All Hud",
    streamerMode: "Streamer Mode",
    refreshRateSpeed: "Refresh Rate Speed",
    refreshRate: "Refresh Rate",
    hideFocus: "Hide Focus",
    hidePlayerId: "Hide Player ID",
    hideBlackMoney: "Hide Black Money",
    hideCoin: "Hide Coin",
    hideUserMoney: "Hide User Money",
    hideServerLogo: "Hide Server Logo",
    hideQuickInfo: "Hide Quick Info",
    hideCashMoney: "Hide Online Users",
    serverInfoStyle: "Server Info Style",
    units: "Units",
    transform: "Transform",
    speedometerType: "Speedometer",
    statusStyleType: "Status Style",
    allStatus: "Hide All Status",
    health: "Hide Health",
    thirst: "Hide Thirst",
    hunger: "Hide Hunger",
    energy: "Hide Energy",
    armor: "Hide Armor",
    stress: "Hide Stress",
    oxygen: "Hide Oxygen",
    playingNow: "Playing Now",
    addSong: "Add Song",
    musicPlayer: "Music Player",
    musicList: "Music List",
    bonnet: "Bonnet",
    leftFrontDoor: "Left Front Door",
    rightFrontDoor: "Right Front Door",
    leftBackDoor: "Left Back Door",
    rightBackDoor: "Right Back Door",
    trunk: "Trunk",
    all: "ALL",
    front: "FRONT",
    left: "LEFT",
    right: "RIGHT",
    rear: "REAR",
    party: "PARTY",
    caps: "CAPS",
    onOffSettings: "Off-On Settings",
    showMyID: "Show My ID",
    playMediaSongs: "Play Media Songs",
    enableStreamerMode: "Enable Streamer Mode",
    modeOn: "MODE ON",
    realTime: "Real Time",
    high: "High",
    medium: "Medium",
    low: "Low",
    selectedNow: "Selected Now",
    selected: "Selected",
    select: "Select",
    neverHide: "Never Hide",
    saveSettings: "Save Settings",
    restoreDefaults: "Restore Defaults",
    cancel: "Cancel",
    settings: "Settings",
    exitSettings: "Exit Settings",
    click: "CLICK",
    toSaveSettings: "to Save Settings",
    saveColor: "Save Color",
    bank: "Bank",
    cash: "Cash",
    job: "Job",
    id: "ID",
    money: "Money",
    coin: "Coin",
    media: "Media",
    vehicle: "Vehicle",
    map: "Map",
    doors: "Doors",
    neons: "Neons",
    time: "Time",
    serverName: "Server Name",
    serverLink: "serverlink.com",
  },
  general: {
    cinematicMode: false,
    showLocation: true,
    minimap: true,
    freeformEditMode: false,
    hideAllHud: false,
    streamerMode: false,
    refreshRateSpeed: false,
    refreshRate: "Low",
    hideFocus: false,
    hidePlayerId: false,
  },
  serverInfoSettings: {
    hideBlackMoney: false,
    hideCoin: false,
    hideUserMoney: false,
    hideServerLogo: false,
    hideQuickInfo: false,
    hideCashMoney: false,
    serverInfoStyle: "1",
  },
  speedometers: {
    units: "kmh",
    transform: 90,
    speedometerType: "1",
  },
  status: {
    statusStyleType: "10",
    allStatus: false,
    health: false,
    thirst: false,
    hunger: false,
    energy: false,
    armor: false,
    stress: false,
    oxygen: false,
  },
  styleVisibility: {
    "1": {
      visibilityThresholds: {
        health: 100,
        thirst: 100,
        hunger: 100,
        energy: 100,
        armor: 100,
        stress: 100,
        oxygen: 100,
      },
      visibilityColor: {
        health: "#E12E59",
        thirst: "#882EE1",
        hunger: "#DE2EE1",
        energy: "#E12E39",
        armor: "#2E60E1",
        stress: "#E12E39",
      },
    },
    "2": {
      visibilityThresholds: {
        health: 100,
        thirst: 100,
        hunger: 100,
        energy: 100,
        armor: 100,
        stress: 100,
        oxygen: 100,
      },
      visibilityColor: {
        health: "#ffffff",
        thirst: "#ffffff",
        hunger: "#ffffff",
        energy: "#ffffff",
        armor: "#ffffff",
        stress: "#ffffff",
      },
    },
    "3": {
      visibilityThresholds: {
        health: 100,
        thirst: 100,
        hunger: 100,
        energy: 100,
        armor: 100,
        stress: 100,
        oxygen: 100,
      },
      visibilityColor: {
        health: "#000000",
        thirst: "#000000",
        hunger: "#000000",
        energy: "#000000",
        armor: "#000000",
        stress: "#000000",
      },
    },
    "4": {
      visibilityThresholds: {
        health: 100,
        thirst: 100,
        hunger: 100,
        energy: 100,
        armor: 100,
        stress: 100,
        oxygen: 100,
      },
      visibilityColor: {
        health: "#4D2FA1",
        thirst: "#FF72CF",
        hunger: "#FFA756",
        energy: "#FF7E8A",
        armor: "#FF89D7",
        stress: "#FFBF83",
      },
    },
    "5": {
      visibilityThresholds: {
        health: 100,
        thirst: 100,
        hunger: 100,
        energy: 100,
        armor: 100,
        stress: 100,
        oxygen: 100,
      },
      visibilityColor: {
        health: "#8256FF",
        thirst: "#FF56C5",
        hunger: "#FFA756",
        energy: "#56FFAE",
        armor: "#FF56C5",
        stress: "#FFA756",
      },
    },
    "6": {
      visibilityThresholds: {
        health: 100,
        thirst: 100,
        hunger: 100,
        energy: 100,
        armor: 100,
        stress: 100,
        oxygen: 100,
      },
      visibilityColor: {
        health: "#ffffff",
        thirst: "#ffffff",
        hunger: "#ffffff",
        energy: "#ffffff",
        armor: "#ffffff",
        stress: "#ffffff",
      },
    },
    "7": {
      visibilityThresholds: {
        health: 100,
        thirst: 100,
        hunger: 100,
        energy: 100,
        armor: 100,
        stress: 100,
        oxygen: 100,
      },
      visibilityColor: {
        health: "#FF4758",
        thirst: "#C447FF",
        hunger: "#47A7FF",
        energy: "#FF7347",
        armor: "#FF9F47",
        stress: "#FF9F47",
      },
    },
    "8": {
      visibilityThresholds: {
        health: 100,
        thirst: 100,
        hunger: 100,
        energy: 100,
        armor: 100,
        stress: 100,
        oxygen: 100,
      },
      visibilityColor: {
        health: "#FF56C6",
        thirst: "#8256FF",
        hunger: "#FFA756",
        energy: "#56FFAE",
        armor: "#FC56FF",
        stress: "#56F5FF",
      },
    },
    "9": {
      visibilityThresholds: {
        health: 100,
        thirst: 100,
        hunger: 100,
        energy: 100,
        armor: 100,
        stress: 100,
        oxygen: 100,
      },
      visibilityColor: {
        health: "#FF4758",
        thirst: "#FF7E47",
        hunger: "#56B954",
        energy: "#814BB7",
        armor: "#4982D8",
        stress: "#FF4758",
      },
    },
    "10": {
      visibilityThresholds: {
        health: 100,
        thirst: 100,
        hunger: 100,
        energy: 100,
        armor: 100,
        stress: 100,
        oxygen: 100,
      },
      visibilityColor: {
        health: "#FF5F98",
        thirst: "#FFE24D",
        hunger: "#33DAFF",
        energy: "#33FF85",
        armor: "#5FBCFF",
        stress: "#FF3357",
      },
    },
  },
  carSettings: {
    engineHasProblem: false,
    doorIsOpen: false,
  },
};
