INSERT INTO `items` (`name`, `label`, `weight`) VALUES
  ('cc_bubbletea', 'Bubble Tea', 1),
  ('cc_chocolatemilkshake', 'Chocolate MilkShake', 1),
  ('cc_strawberrysmoothie', 'Strawberry Smoothie', 1),
  ('cc_berryblastsmoothie', 'BerryBlast Smoothie', 1),
  ('cc_tropicalparadisesmoothie', 'Tropical Paradise Smoothie', 1),
  ('cc_fukuoka_hakata_ramen', 'Fukuoka Hakata Ramen', 1),
  ('cc_miso_ramen', 'Miso Ramen', 1),
  ('cc_osaka_shio_ramen', 'Osaka Shio Ramen', 1),
  ('cc_tonkotsu_ramen', 'Tonkotsu Ramen', 1),
  ('cc_iekei_ramen', 'Iekei Ramen', 1),
  ('cc_black_garlic_ramen', 'Black Garlic Ramen', 1),
  ('cc_shoyu_ramen', 'Shoyu Ramen', 1),
  ('cc_nagoya_taiwan_ramen','Nagoya Taiwan Ramen',1),
  ('cc_espresso', 'Espresso', 1),
  ('cc_cappuccino', 'Cappuccino', 1),
  ('cc_latte', 'Latte', 1),
  ('cc_mocha', 'Mocha', 1),
  ('cc_hotchocolate', 'Hot Chocolate', 1),
  ('cc_vanilla_icecream', 'Vanilla Icecream', 1),
  ('cc_chocolate_icecream', 'Chocolate Icecream', 1),
  ('cc_strawberry_icecream', 'Strawberry Icecream', 1),
  ('cc_mintchoco_icecream', 'Mintchoco Icecream', 1),
  ('cc_coffee_icecream', 'Coffee Icecream', 1),
  ('cc_classic_blt_sandwich', 'Classic Blt Sandwich', 1),
  ('cc_cheese_sandwich', 'Cheese Sandwich', 1),
  ('cc_turkey_sandwich', 'Turkey Sandwich', 1),
  ('cc_caprese_sandwich', 'Caprese Sandwich', 1),
  ('cc_avocado_sandwich', 'Avocado Sandwich', 1),
  ('cc_miso_broth', 'Miso Broth', 1),
  ('cc_cocao_powder', 'Cocoa Powder',1),
  ('cc_black_tapioca_pearls', 'Black Tapioca Pearls', 1),
  ('cc_brewed_black_tea', 'Brewed Black Tea', 1),
  ('cc_milk', 'Milk', 1),
  ('cc_chocolate_syrup', 'Chocolate Syrup', 1),
  ('cc_strawberries', 'Strawberries', 1),
  ('cc_ripebanana', 'Ripe Banana', 1),
  ('cc_yogurtcup', 'Yogurt Cup', 1),
  ('cc_cuporangejuice', 'Cup of Orange Juice', 1),
  ('cc_mixedberries', 'Mixed Berries', 1),
  ('cc_pineapple_chunks', 'Pineapple Chunks', 1),
  ('cc_mango_chunks', 'Mango Chunks', 1),
  ('cc_coconut_milk', 'Coconut Milk', 1),
  ('cc_pure_vanilla', 'Pure Vanilla', 1),
  ('cc_heavy_cream', 'Heavy Cream', 1),
  ('cc_chocolate_chips', 'Chocolate Chips', 1),
  ('cc_coffee_powder', 'Coffee Powder', 1),
  ('cc_chocolate_cookies', 'Chocolate Cookies', 1),
  ('cc_wheat_noodles', 'Wheat Noodles', 1),
  ('cc_green_onions', 'Green Onions', 1),
  ('cc_chashu_pork', 'Chashu Pork', 1),
  ('cc_butter', 'Butter', 1),
  ('cc_spinach', 'Spinach', 1),
  ('cc_soft_boiled_egg', 'Soft Boiled Egg', 1),
  ('cc_sugar', 'Sugar', 1),
  ('cc_bacon_strips', 'Bacon Strips', 1),
  ('cc_slices_of_bread', 'Slices of Bread', 1),
  ('cc_lettuce', 'Lettuce', 1),
  ('cc_cheddar_cheese', 'Cheddar Cheese', 1),
  ('cc_turkey_slices', 'Turkey Slices', 1),
  ('cc_mozzarella_cheese', 'Mozzarella Cheese', 1),
  ('cc_avocado', 'Avocado', 1),
  ('cc_icecubes', 'Ice Cubes', 1),
  ('cc_emptycup', 'Empty Cup', 1),
  ('cc_waterbottle', 'Water Bottle', 1),
  --toys
  ('plush_01a', 'Plush Toy 01', 1),
  ('plush_02a', 'Plush Toy 02', 1),
  ('plush_03a', 'Plush Toy 03', 1),
  ('plush_04a', 'Plush Toy 04', 1),
  ('plush_05a', 'Plush Toy 05', 1),
  ('plush_06a', 'Plush Toy 06', 1),
  ('plush_07a', 'Plush Toy 07', 1),
  ('plush_08a', 'Plush Toy 08', 1);
  